-- Generated from frontend/src/data/menu-mock.json.
-- Do not edit rows manually; update the JSON source or the generator script.

begin;

insert into menu_categories (name, slug, display_order)
values
    ('Uramaki / Hossomaki (6pcs)', 'uramaki-hossomaki-6pcs', 10),
    ('Nigiri (2pcs)', 'nigiri-2pcs', 20),
    ('Signature Rolls (8pcs)', 'signature-rolls-8pcs', 30),
    ('Raw', 'raw', 40),
    ('Crispy Fried Rolls (6pcs)', 'crispy-fried-rolls-6pcs', 50),
    ('Bites', 'bites', 60),
    ('Bao Buns (2pcs)', 'bao-buns-2pcs', 70),
    ('Noodles', 'noodles', 80),
    ('Burger & Sando (served with fries)', 'burger-sando-served-with-fries', 90),
    ('Poke Bowl', 'poke-bowl', 100),
    ('Salads', 'salads', 110),
    ('Desserts', 'desserts', 120),
    ('Masao Cocktails', 'masao-cocktails', 130),
    ('Classic Cocktails', 'classic-cocktails', 140),
    ('Mocktails', 'mocktails', 150),
    ('Soft Drinks', 'soft-drinks', 160),
    ('Ciders', 'ciders', 170),
    ('Beers', 'beers', 180),
    ('Whiskey', 'whiskey', 190),
    ('White Wines', 'white-wines', 200),
    ('Rose Wines', 'rose-wines', 210),
    ('Red Wines', 'red-wines', 220),
    ('Champagne & Sparkling', 'champagne-sparkling', 230),
    ('Shisha', 'shisha', 240)
on conflict (name) do update
set
    slug = excluded.slug,
    display_order = excluded.display_order;

insert into menu_category_translations (category_id, language_code, name)
select c.id, v.language_code, v.name
from (
    values
    ('Bao Buns (2pcs)', 'de', 'Bao Buns (2 Stück)'),
    ('Bao Buns (2pcs)', 'el', 'Bao Buns (2pcs)'),
    ('Bao Buns (2pcs)', 'en', 'Bao Buns (2pcs)'),
    ('Bao Buns (2pcs)', 'it', 'Bao Buns (2 pezzi)'),
    ('Bao Buns (2pcs)', 'sv', 'Bao Bröd (2 bitar)'),
    ('Beers', 'de', 'Biere'),
    ('Beers', 'el', 'Beers'),
    ('Beers', 'en', 'Beers'),
    ('Beers', 'it', 'Birre'),
    ('Beers', 'sv', 'Öl'),
    ('Bites', 'de', 'Häppchen'),
    ('Bites', 'el', 'Bites'),
    ('Bites', 'en', 'Bites'),
    ('Bites', 'it', 'Bocconcini'),
    ('Bites', 'sv', 'Smårätter'),
    ('Burger & Sando (served with fries)', 'de', 'Burger & Sando (mit Pommes serviert)'),
    ('Burger & Sando (served with fries)', 'el', 'Burger & Sando (served with fries)'),
    ('Burger & Sando (served with fries)', 'en', 'Burger & Sando (served with fries)'),
    ('Burger & Sando (served with fries)', 'it', 'Burger & Sando (servito con patatine)'),
    ('Burger & Sando (served with fries)', 'sv', 'Burger & Sando (serveras med pommes)'),
    ('Champagne & Sparkling', 'de', 'Champagner & Sekt'),
    ('Champagne & Sparkling', 'el', 'Champagne & Sparkling'),
    ('Champagne & Sparkling', 'en', 'Champagne & Sparkling'),
    ('Champagne & Sparkling', 'it', 'Champagne & Spumanti'),
    ('Champagne & Sparkling', 'sv', 'Champagne & Mousserande'),
    ('Ciders', 'de', 'Cider'),
    ('Ciders', 'el', 'Ciders'),
    ('Ciders', 'en', 'Ciders'),
    ('Ciders', 'it', 'Sidro'),
    ('Ciders', 'sv', 'Cider'),
    ('Classic Cocktails', 'de', 'Klassische Cocktails'),
    ('Classic Cocktails', 'el', 'Classic Cocktails'),
    ('Classic Cocktails', 'en', 'Classic Cocktails'),
    ('Classic Cocktails', 'it', 'Cocktail Classici'),
    ('Classic Cocktails', 'sv', 'Klassiska Cocktails'),
    ('Crispy Fried Rolls (6pcs)', 'de', 'Knusprige Frittierte Rollen (6 Stück)'),
    ('Crispy Fried Rolls (6pcs)', 'el', 'Crispy Fried Rolls (6pcs)'),
    ('Crispy Fried Rolls (6pcs)', 'en', 'Crispy Fried Rolls (6pcs)'),
    ('Crispy Fried Rolls (6pcs)', 'it', 'Rolls Fritti Croccanti (6 pezzi)'),
    ('Crispy Fried Rolls (6pcs)', 'sv', 'Krispiga Friterade Rullar (6 bitar)'),
    ('Desserts', 'de', 'Desserts'),
    ('Desserts', 'el', 'Desserts'),
    ('Desserts', 'en', 'Desserts'),
    ('Desserts', 'it', 'Dolci'),
    ('Desserts', 'sv', 'Desserter'),
    ('Masao Cocktails', 'de', 'Masao Cocktails'),
    ('Masao Cocktails', 'el', 'Masao Cocktails'),
    ('Masao Cocktails', 'en', 'Masao Cocktails'),
    ('Masao Cocktails', 'it', 'Cocktail Masao'),
    ('Masao Cocktails', 'sv', 'Masao Cocktails'),
    ('Mocktails', 'de', 'Alkoholfreie Cocktails'),
    ('Mocktails', 'el', 'Mocktails'),
    ('Mocktails', 'en', 'Mocktails'),
    ('Mocktails', 'it', 'Cocktail Analcolici'),
    ('Mocktails', 'sv', 'Alkoholfria Cocktails'),
    ('Nigiri (2pcs)', 'de', 'Nigiri (2 Stück)'),
    ('Nigiri (2pcs)', 'el', 'Nigiri (2pcs)'),
    ('Nigiri (2pcs)', 'en', 'Nigiri (2pcs)'),
    ('Nigiri (2pcs)', 'it', 'Nigiri (2 pezzi)'),
    ('Nigiri (2pcs)', 'sv', 'Nigiri (2 bitar)'),
    ('Noodles', 'de', 'Nudeln'),
    ('Noodles', 'el', 'Noodles'),
    ('Noodles', 'en', 'Noodles'),
    ('Noodles', 'it', 'Noodles'),
    ('Noodles', 'sv', 'Nudlar'),
    ('Poke Bowl', 'de', 'Poke Bowl'),
    ('Poke Bowl', 'el', 'Poke Bowl'),
    ('Poke Bowl', 'en', 'Poke Bowl'),
    ('Poke Bowl', 'it', 'Poke Bowl'),
    ('Poke Bowl', 'sv', 'Poke Bowl'),
    ('Raw', 'de', 'Roh'),
    ('Raw', 'el', 'Raw'),
    ('Raw', 'en', 'Raw'),
    ('Raw', 'it', 'Crudo'),
    ('Raw', 'sv', 'Rå'),
    ('Red Wines', 'de', 'Rotweine'),
    ('Red Wines', 'el', 'Red Wines'),
    ('Red Wines', 'en', 'Red Wines'),
    ('Red Wines', 'it', 'Vini Rossi'),
    ('Red Wines', 'sv', 'Röda Viner'),
    ('Rose Wines', 'de', 'Roséweine'),
    ('Rose Wines', 'el', 'Rose Wines'),
    ('Rose Wines', 'en', 'Rosé Wines'),
    ('Rose Wines', 'it', 'Vini Rosati'),
    ('Rose Wines', 'sv', 'Rosévin'),
    ('Salads', 'de', 'Salate'),
    ('Salads', 'el', 'Salads'),
    ('Salads', 'en', 'Salads'),
    ('Salads', 'it', 'Insalate'),
    ('Salads', 'sv', 'Sallader'),
    ('Shisha', 'de', 'Shisha'),
    ('Shisha', 'el', 'Shisha'),
    ('Shisha', 'en', 'Shisha'),
    ('Shisha', 'it', 'Shisha'),
    ('Shisha', 'sv', 'Shisha'),
    ('Signature Rolls (8pcs)', 'de', 'Signature Rolls (8 Stück)'),
    ('Signature Rolls (8pcs)', 'el', 'Signature Rolls (8pcs)'),
    ('Signature Rolls (8pcs)', 'en', 'Signature Rolls (8pcs)'),
    ('Signature Rolls (8pcs)', 'it', 'Signature Rolls (8 pezzi)'),
    ('Signature Rolls (8pcs)', 'sv', 'Signature Rolls (8 bitar)'),
    ('Soft Drinks', 'de', 'Erfrischungsgetränke'),
    ('Soft Drinks', 'el', 'Soft Drinks'),
    ('Soft Drinks', 'en', 'Soft Drinks'),
    ('Soft Drinks', 'it', 'Bibite'),
    ('Soft Drinks', 'sv', 'Läskedrycker'),
    ('Uramaki / Hossomaki (6pcs)', 'de', 'Uramaki / Hossomaki (6 Stück)'),
    ('Uramaki / Hossomaki (6pcs)', 'el', 'Uramaki / Hossomaki (6pcs)'),
    ('Uramaki / Hossomaki (6pcs)', 'en', 'Uramaki / Hossomaki (6pcs)'),
    ('Uramaki / Hossomaki (6pcs)', 'it', 'Uramaki / Hossomaki (6 pezzi)'),
    ('Uramaki / Hossomaki (6pcs)', 'sv', 'Uramaki / Hossomaki (6 bitar)'),
    ('Whiskey', 'de', 'Whisky'),
    ('Whiskey', 'el', 'Whiskey'),
    ('Whiskey', 'en', 'Whiskey'),
    ('Whiskey', 'it', 'Whiskey'),
    ('Whiskey', 'sv', 'Whisky'),
    ('White Wines', 'de', 'Weißweine'),
    ('White Wines', 'el', 'White Wines'),
    ('White Wines', 'en', 'White Wines'),
    ('White Wines', 'it', 'Vini Bianchi'),
    ('White Wines', 'sv', 'Vita Viner')
) as v(category_name, language_code, name)
join menu_categories c on c.name = v.category_name
on conflict (category_id, language_code) do update
set
    name = excluded.name,
    updated_at = now();

insert into menu_items (external_id, category_id, name, description, price, tags, is_available, display_order)
select v.external_id, c.id, v.name, v.description, v.price, v.tags, true, v.display_order
from (
    values
    ('UR001', 'Uramaki / Hossomaki (6pcs)', 'Cucumber Maki', 'cucumber', 8.00, array['ελαφρύ', 'δροσερό', 'vegan-friendly', 'χορτοφαγικό']::text[], 1),
    ('UR002', 'Uramaki / Hossomaki (6pcs)', 'Avocado Maki', 'avocado', 8.00, array['ελαφρύ', 'κρεμώδες', 'vegan-friendly', 'χορτοφαγικό']::text[], 2),
    ('UR003', 'Uramaki / Hossomaki (6pcs)', 'Veggie Roll', 'cucumber, avocado, mango, spring onion, cream cheese, green tobico', 8.70, array['γλυκόξινο', 'φρουτώδες', 'κρεμώδες']::text[], 3),
    ('UR004', 'Uramaki / Hossomaki (6pcs)', 'Vegan Roll', 'cucumber, avocado, mango, spring onion, vegan mayo, sesame', 8.70, array['γλυκόξινο', 'φρουτώδες', 'vegan', 'ελαφρύ']::text[], 4),
    ('UR005', 'Uramaki / Hossomaki (6pcs)', 'California Salmon', 'salmon, cucumber, avocado, cream cheese, sesame', 9.70, array['κρεμώδες', 'πλούσιο', 'κλασικό']::text[], 5),
    ('UR006', 'Uramaki / Hossomaki (6pcs)', 'California Crab', 'crab kanimi, cucumber, avocado, cream mayo, sesame', 9.20, array['κρεμώδες', 'ελαφρύ', 'κλασικό']::text[], 6),
    ('UR007', 'Uramaki / Hossomaki (6pcs)', 'Shrimp Tempura', 'shrimp tempura, avocado, spicy mayo, red masago', 9.30, array['πικάντικο', 'τραγανό', 'πλούσιο', 'umami']::text[], 7),
    ('UR008', 'Uramaki / Hossomaki (6pcs)', 'Tekka Kimchi', 'tuna, cucumber, fried garlic, kimchi mayo, kimchi sesame', 9.90, array['πικάντικο', 'umami', 'έντονο', 'fermented']::text[], 8),
    ('UR009', 'Uramaki / Hossomaki (6pcs)', 'Spicy Suzuki', 'sea bass, cucumber, avocado, chilli mayo, yuzu, tobico', 9.50, array['πικάντικο', 'εσπεριδοειδές', 'δροσερό', 'ελαφρύ']::text[], 9),
    ('NI001', 'Nigiri (2pcs)', 'Avocado Nigiri', 'avocado', 3.80, array['ελαφρύ', 'κρεμώδες', 'vegan-friendly', 'χορτοφαγικό']::text[], 10),
    ('NI002', 'Nigiri (2pcs)', 'Salmon Nigiri', 'salmon', 4.50, array['βουτυράτο', 'φρέσκο', 'κλασικό', 'umami']::text[], 11),
    ('NI003', 'Nigiri (2pcs)', 'Tuna Nigiri', 'tuna', 4.80, array['άπαχο', 'φρέσκο', 'κλασικό', 'umami']::text[], 12),
    ('NI004', 'Nigiri (2pcs)', 'Sea Bass Nigiri', 'sea bass', 4.50, array['ελαφρύ', 'φρέσκο', 'λεπτό']::text[], 13),
    ('NI005', 'Nigiri (2pcs)', 'Shrimp Nigiri', 'shrimp', 4.00, array['γλυκό', 'ελαφρύ', 'θαλασσινό']::text[], 14),
    ('NI006', 'Nigiri (2pcs)', 'Smoked Eel Nigiri', 'smoked eel', 5.00, array['καπνιστό', 'πλούσιο', 'γλυκόξινο', 'umami']::text[], 15),
    ('SR001', 'Signature Rolls (8pcs)', 'Mango Mango', 'Inside: shrimp tempura, cream cheese. On top: mango, passion fruit mayo, sesame, chives', 18.00, array['φρουτώδες', 'γλυκό', 'τροπικό', 'κρεμώδες']::text[], 16),
    ('SR002', 'Signature Rolls (8pcs)', 'Crab & Tuna', 'Inside: tuna, avocado, cucumber, spring onion. On top: crab, spicy mayo, chives, crispy onion', 18.50, array['πικάντικο', 'τραγανό', 'umami', 'πλούσιο']::text[], 17),
    ('SR003', 'Signature Rolls (8pcs)', 'Spicy Tuna', 'Inside: tuna, avocado, cucumber. On top: tuna sashimi, spicy mayo, togarashi, chives', 18.00, array['πικάντικο', 'έντονο', 'umami', 'φρέσκο']::text[], 18),
    ('SR004', 'Signature Rolls (8pcs)', 'Salmon Truffle', 'Inside: salmon, cucumber, spring onion. On top: seared salmon, unagi sauce, truffle mayo, crispy garlic, caviar', 18.00, array['πολυτελές', 'umami', 'καπνιστό', 'βαθύ άρωμα']::text[], 19),
    ('SR005', 'Signature Rolls (8pcs)', 'Phili Salmon', 'Inside: salmon, cream cheese, mango. On top: salmon tartare, sweet chili mayo, ikura, spring onions', 18.00, array['γλυκόξινο', 'κρεμώδες', 'φρουτώδες', 'πλούσιο']::text[], 20),
    ('SR006', 'Signature Rolls (8pcs)', 'Suzuki & Shrimp', 'Inside: shrimp tempura, cream cheese, mango. On top: seared sea bass, sweet spicy mayo, teriyaki, spring onions, tobico', 18.50, array['γλυκόπικρο', 'φρουτώδες', 'τραγανό', 'πλούσιο']::text[], 21),
    ('SR007', 'Signature Rolls (8pcs)', 'Crispy Shrimp', 'Inside: shrimp tempura, spring onion, cream cheese. On top: avocado, spicy mayo, crispy onion, chives', 18.50, array['τραγανό', 'πικάντικο', 'κρεμώδες', 'πλούσιο']::text[], 22),
    ('SR008', 'Signature Rolls (8pcs)', 'Chicken Roll', 'Inside: crispy chicken, iceberg lettuce, spring onion. On top: avocado, crispy onion, hoisin mayo', 18.00, array['τραγανό', 'ελαφρύ', 'γλυκόξινο', 'comfort food']::text[], 23),
    ('SR009', 'Signature Rolls (8pcs)', 'Masao', 'Inside: shrimp tempura, avocado, spring onion. On top: beef tartare, truffle mayo, crispy onion, chives', 21.00, array['πολυτελές', 'πλούσιο', 'βαθύ άρωμα', 'signature']::text[], 24),
    ('SR010', 'Signature Rolls (8pcs)', 'Aegean Roll', 'Inside: cucumber, avocado, feta cheese. On top: seared sea bass, lime mayo, olive oil, dill, sesame', 19.00, array['μεσογειακό', 'φρέσκο', 'ελαφρύ', 'ελληνικό']::text[], 25),
    ('RAW001', 'Raw', 'Sea Bass Carpaccio', 'sea bass, citrus, red pepper, yuzu, chilli, olive oil, lemon, dill', 19.50, array['εσπεριδοειδές', 'δροσερό', 'πικάντικο', 'ελαφρύ', 'φρέσκο']::text[], 26),
    ('RAW002', 'Raw', 'Salmon Yuzu', 'salmon, ikura, lime zest, spring onion, mango, yuzu, sesame', 19.70, array['εσπεριδοειδές', 'φρουτώδες', 'φρέσκο', 'ελαφρύ']::text[], 27),
    ('RAW003', 'Raw', 'Tuna Turf', 'tuna, truffle oil, cherry tomato, parsley, spring onion', 20.00, array['βαθύ άρωμα', 'umami', 'πλούσιο', 'μεσογειακό']::text[], 28),
    ('RAW004', 'Raw', 'Variety of Sashimi 12pcs', 'salmon, tuna, sea bass', 20.00, array['φρέσκο', 'ελαφρύ', 'κλασικό', 'ποικιλία']::text[], 29),
    ('CF001', 'Crispy Fried Rolls (6pcs)', 'Crispy Tekka Roll', 'Inside: tuna, cucumber, cream cheese. On top: spicy mayo, teriyaki, chives', 14.00, array['τραγανό', 'πικάντικο', 'γλυκόξινο', 'umami']::text[], 30),
    ('CF002', 'Crispy Fried Rolls (6pcs)', 'Crunchy Salmon Roll', 'Inside: salmon, cream cheese, avocado. On top: hoisin mayo, chives', 13.00, array['τραγανό', 'κρεμώδες', 'γλυκόξινο', 'comfort food']::text[], 31),
    ('CF003', 'Crispy Fried Rolls (6pcs)', 'Crispy Veggie Roll', 'Inside: cucumber, cream cheese, avocado. On top: hoisin mayo, chives', 10.00, array['τραγανό', 'κρεμώδες', 'ελαφρύ', 'χορτοφαγικό']::text[], 32),
    ('BI001', 'Bites', 'Chicken Dumplings', 'truffle ponzu sauce, spring onion', 9.50, array['umami', 'βαθύ άρωμα', 'ζουμερό', 'comfort food']::text[], 33),
    ('BI002', 'Bites', 'Spring Rolls', 'vegetable spring rolls, sweet chilli sauce', 8.50, array['τραγανό', 'γλυκόξινο', 'ελαφρύ', 'χορτοφαγικό', 'vegan-friendly']::text[], 34),
    ('BI003', 'Bites', 'Shrimp Gyoza', 'chilli soy sauce, chives', 9.90, array['umami', 'πικάντικο', 'ζουμερό', 'αλμυρό']::text[], 35),
    ('BI004', 'Bites', 'Crispy Cheese Wonton', 'shrimp, crab, cream cheese', 8.50, array['τραγανό', 'κρεμώδες', 'πλούσιο', 'indulgent']::text[], 36),
    ('BAO001', 'Bao Buns (2pcs)', 'Shrimp Bao', 'shrimp tempura, cucumber, avocado cream, lettuce, spicy mayo, chives, sesame', 12.50, array['τραγανό', 'κρεμώδες', 'πικάντικο', 'comfort food']::text[], 37),
    ('BAO002', 'Bao Buns (2pcs)', 'Chicken Bao', 'crispy chicken, cucumber, avocado cream, lettuce, spicy mayo, chives, crispy onion', 12.00, array['τραγανό', 'ελαφρύ', 'γλυκόξινο', 'comfort food']::text[], 38),
    ('BAO003', 'Bao Buns (2pcs)', 'Salmon Bao', 'salmon teriyaki, cucumber, lettuce, avocado, lime mayo, chives, crispy onion', 12.50, array['γλυκόξινο', 'φρέσκο', 'εσπεριδοειδές', 'ελαφρύ']::text[], 39),
    ('BAO004', 'Bao Buns (2pcs)', 'Mushroom Bao', 'mushroom, cucumber, hoisin mayo, spring onion, sesame', 12.00, array['umami', 'γλυκόξινο', 'χορτοφαγικό', 'βαθύ γεύση']::text[], 40),
    ('BAO005', 'Bao Buns (2pcs)', 'Duck Bao', 'crispy duck, cucumber, lettuce, carrot, plum sauce, chives, sesame', 15.00, array['τραγανό', 'γλυκόξινο', 'πλούσιο', 'εξωτικό']::text[], 41),
    ('NO001', 'Noodles', 'Veggie Noodles', 'cabbage, onion, carrot, peppers, baby corn, noodles, sesame oil, teriyaki sauce', 9.80, array['ελαφρύ', 'γλυκόξινο', 'χορτοφαγικό', 'vegan-friendly']::text[], 42),
    ('NO002', 'Noodles', 'Chicken Noodles', 'cabbage, onion, carrot, peppers, baby corn, egg noodles, sesame oil, teriyaki sauce', 13.00, array['ελαφρύ', 'γλυκόξινο', 'comfort food', 'αλμυρό']::text[], 43),
    ('NO003', 'Noodles', 'Shrimp Noodles', 'cabbage, onion, carrot, peppers, baby corn, noodles, sesame oil, teriyaki sauce', 15.00, array['ελαφρύ', 'γλυκόξινο', 'θαλασσινό', 'umami']::text[], 44),
    ('NO004', 'Noodles', 'Mushroom Yaki Udon', 'mushrooms, udon noodles, spring onion, garlic, ginger, unagi sauce', 13.00, array['umami', 'βαθύ γεύση', 'ζεστό', 'χορτοφαγικό']::text[], 45),
    ('NO005', 'Noodles', 'Salmon Yaki Udon', 'glazed salmon fillet, udon noodles, spring onion, carrot, pepper, garlic, ginger, unagi sauce', 16.00, array['βουτυράτο', 'umami', 'πλούσιο', 'γλυκόξινο']::text[], 46),
    ('NO006', 'Noodles', 'Beef Yaki Udon', 'minced beef, udon noodles, spring onion, garlic, ginger, unagi sauce', 16.00, array['πλούσιο', 'umami', 'comfort food', 'έντονο']::text[], 47),
    ('BU001', 'Burger & Sando (served with fries)', 'Beef Melt', 'black angus beef burger, brioche bun, iceberg lettuce, jalapeño peppers, cheddar cheese, hoisin mayo', 14.50, array['πικάντικο', 'πλούσιο', 'αλμυρό', 'comfort food']::text[], 48),
    ('BU002', 'Burger & Sando (served with fries)', 'Beef Truffle', 'black angus beef burger, brioche bun, mixed leaves, parmesan cheese, truffle mayo', 16.00, array['πολυτελές', 'βαθύ άρωμα', 'πλούσιο', 'umami']::text[], 49),
    ('BU003', 'Burger & Sando (served with fries)', 'Chicken Katsu Sando', 'crispy chicken thigh, brioche bun, pickled cucumber, iceberg lettuce, hoisin mayo', 13.50, array['τραγανό', 'γλυκόξινο', 'ελαφρύ', 'comfort food']::text[], 50),
    ('BU004', 'Burger & Sando (served with fries)', 'Shrimp & Crab Sando Roll', 'shrimp, crab, brioche bun, iceberg lettuce, pickled red onion, crispy garlic, chives, spicy mayo', 14.00, array['πικάντικο', 'τραγανό', 'θαλασσινό', 'γλυκόξινο']::text[], 51),
    ('PO001', 'Poke Bowl', 'Salmon Poke Bowl', 'sushi rice, marinated salmon, avocado, cucumber, mango, edamame, wakame, tobico, chives, lime, sesame, spicy mayo', 14.00, array['φρέσκο', 'τροπικό', 'γλυκόξινο', 'ελαφρύ', 'healthy']::text[], 52),
    ('PO002', 'Poke Bowl', 'Shrimp-Crab Poke Bowl', 'sushi rice, poached shrimp, crab kanimi, avocado, cucumber, mango, edamame, wakame, tobico, chives, lime, sesame, spicy mayo', 14.50, array['φρέσκο', 'τροπικό', 'ελαφρύ', 'θαλασσινό', 'healthy']::text[], 53),
    ('PO003', 'Poke Bowl', 'Chicken Poke Bowl', 'sushi rice, crispy chicken, cucumber, avocado, sweet corn, scallions, seaweed, mango, carrot, mayo, sesame', 14.00, array['τραγανό', 'ελαφρύ', 'φρουτώδες', 'comfort food', 'healthy']::text[], 54),
    ('SA001', 'Salads', 'Edamame', 'steamed edamame, salt flakes', 5.50, array['ελαφρύ', 'αλμυρό', 'healthy', 'vegan', 'απλό']::text[], 55),
    ('SA002', 'Salads', 'Kanimi Salad', 'crab kanimi, lettuce, cucumber, spring onion, chili, crispy rice, crispy garlic, sesame dressing', 13.50, array['τραγανό', 'πικάντικο', 'ελαφρύ', 'φρέσκο']::text[], 56),
    ('SA003', 'Salads', 'Emperor Salad', 'crispy chicken, iceberg, lettuce, avocado, crispy bacon, cashew nuts, parmesan dressing', 16.00, array['τραγανό', 'πλούσιο', 'αλμυρό', 'comfort food']::text[], 57),
    ('SA004', 'Salads', 'Kaiso Salad', 'wakame seaweed, sesame', 5.50, array['ελαφρύ', 'umami', 'vegan', 'healthy', 'θαλάσσιο']::text[], 58),
    ('SA005', 'Salads', 'Shrimp Noodle Salad', 'shrimp, mixed leaves, mendake noodles, edamame, avocado, parmesan, peppers, spicy lime dressing', 14.50, array['πικάντικο', 'εσπεριδοειδές', 'ελαφρύ', 'healthy', 'φρέσκο']::text[], 59),
    ('SA006', 'Salads', 'Tropical Shrimp Salad', 'shrimp, cucumber, mango, avocado, mixed leaves, passion fruit mayo, sesame', 14.00, array['τροπικό', 'φρουτώδες', 'γλυκό', 'φρέσκο', 'ελαφρύ']::text[], 60),
    ('DE001', 'Desserts', 'Chocolate Fondant', 'served with pistachio ice cream and cream', 8.50, array['γλυκό', 'ζεστό', 'πλούσιο', 'indulgent', 'σοκολάτα']::text[], 61),
    ('DE002', 'Desserts', 'Baked Cheesecake', 'served with red fruits ice cream and berries', 8.50, array['γλυκό', 'κρεμώδες', 'φρουτώδες', 'ελαφρύ']::text[], 62),
    ('DE003', 'Desserts', 'Tiramisu', 'served with vanilla ice cream and cream', 8.50, array['γλυκό', 'κρεμώδες', 'καφέ', 'κλασικό', 'indulgent']::text[], 63),
    ('CO001', 'Masao Cocktails', 'Okinawa', 'Japanese Yuzu Aperitif, Shiso, Elderflower, Carbonated Sake, Strawberry', 10.00, array['εσπεριδοειδές', 'φρουτώδες', 'δροσερό', 'ανθισμένο', 'ελαφρύ']::text[], 64),
    ('CO002', 'Masao Cocktails', 'Chihaya', 'Don Julio Tequila Blanco, Cardamom-Mustard, Cherries, Nuts, Plum Bitters, Clouds', 13.00, array['σύνθετο', 'πικρό', 'φρουτώδες', 'δυνατό']::text[], 65),
    ('CO003', 'Masao Cocktails', 'Shirakawa', 'Spiced Ketel One Vodka, Hibiscus, Rum, Berries, Ginger Foam', 12.00, array['φρουτώδες', 'αρωματικό', 'δροσερό', 'αφρώδες']::text[], 66),
    ('CO004', 'Masao Cocktails', 'Tsumago', 'Johnnie Walker Black Label, Smoke, Pineapple, Jalapeño, Honey, Lemon Juice', 12.00, array['καπνιστό', 'γλυκόπικρο', 'τροπικό', 'πικάντικο']::text[], 67),
    ('CO005', 'Masao Cocktails', 'ギリシャ (Girisha)', 'Mastiha, Oolong Tea, Ponzu Citrus, Pickled Peach, Aromatic Bitters', 11.00, array['ελληνικό', 'εσπεριδοειδές', 'αρωματικό', 'πικρό', 'signature']::text[], 68),
    ('CO006', 'Masao Cocktails', 'Japanese Opioum', 'Vodka, Citron Liqueur, Jasmine Syrup, Lime Juice, Green Apple Liqueur', 12.00, array['εσπεριδοειδές', 'φρουτώδες', 'ανθισμένο', 'δροσερό']::text[], 69),
    ('CO007', 'Masao Cocktails', 'Yugen', 'Tanqueray No. 10 Gin, Mandarin, Botanicals, Lemon Juice, Yuzu Coconut Foam', 14.00, array['εσπεριδοειδές', 'αρωματικό', 'αφρώδες', 'τροπικό']::text[], 70),
    ('CO008', 'Masao Cocktails', 'Kintsugi Sour', 'Johnnie Walker Black Ruby, Vanilla, Banana, Lemon Peel, Lime, Clouds', 11.00, array['εσπεριδοειδές', 'φρουτώδες', 'αφρώδες', 'γλυκόξινο']::text[], 71),
    ('CO009', 'Masao Cocktails', 'Tsukimi Glow', 'Tanqueray Gin, Passion Fruit, Rhubarb Liqueur, Pink Grapefruit Soda', 11.00, array['τροπικό', 'φρουτώδες', 'δροσερό', 'αφρώδες']::text[], 72),
    ('CO010', 'Masao Cocktails', 'Amaterasu Light', 'Captain Morgan Rum, Zacapa Rum, Melon, Lemon Juice, Mint Leaves', 11.00, array['φρουτώδες', 'δροσερό', 'γλυκό', 'μέντα']::text[], 73),
    ('CC001', 'Classic Cocktails', 'Margarita', 'Tequila, triple sec, lime juice, salt rim', 12.00, array['εσπεριδοειδές', 'κλασικό', 'αλμυρό', 'δροσερό']::text[], 74),
    ('CC002', 'Classic Cocktails', 'Daiquiri', 'Rum, lime juice, sugar', 11.00, array['εσπεριδοειδές', 'κλασικό', 'δροσερό', 'γλυκόξινο']::text[], 75),
    ('CC003', 'Classic Cocktails', 'Porn Star Martini', 'Vanilla vodka, passion fruit liqueur, passion fruit, prosecco', 11.00, array['φρουτώδες', 'γλυκό', 'τροπικό', 'κλασικό']::text[], 76),
    ('CC004', 'Classic Cocktails', 'Gin Basil Smash', 'Gin, fresh basil, lemon juice, sugar syrup', 10.00, array['φρέσκο', 'βότανα', 'εσπεριδοειδές', 'δροσερό']::text[], 77),
    ('CC005', 'Classic Cocktails', 'Paloma', 'Tequila, grapefruit soda, lime juice, salt', 12.00, array['εσπεριδοειδές', 'δροσερό', 'γλυκόξινο', 'κλασικό']::text[], 78),
    ('CC006', 'Classic Cocktails', 'Mai Tai', 'Rum, orange curaçao, lime juice, orgeat syrup', 12.00, array['τροπικό', 'φρουτώδες', 'γλυκό', 'κλασικό']::text[], 79),
    ('CC007', 'Classic Cocktails', 'Zombie', 'Three types of rum, fruit juices, grenadine', 12.00, array['τροπικό', 'δυνατό', 'φρουτώδες', 'έντονο']::text[], 80),
    ('CC008', 'Classic Cocktails', 'Espresso Martini', 'Vodka, coffee liqueur, espresso, sugar syrup', 11.00, array['καφέ', 'γλυκό', 'δυνατό', 'κλασικό']::text[], 81),
    ('CC009', 'Classic Cocktails', 'Long Drinks', 'Classic long drinks selection', 9.00, array['δροσερό', 'ελαφρύ', 'κλασικό']::text[], 82),
    ('MO001', 'Mocktails', 'Takaragawa', 'Tanqueray 0%, cherries, pickled peach', 9.00, array['φρουτώδες', 'γλυκόξινο', 'alcohol-free', 'δροσερό']::text[], 83),
    ('MO002', 'Mocktails', 'Bonsai Breeze', 'Tanqueray 0%, passion fruit, tangerine, black tea, lemon juice', 10.00, array['τροπικό', 'εσπεριδοειδές', 'alcohol-free', 'δροσερό', 'φρουτώδες']::text[], 84),
    ('DR001', 'Soft Drinks', 'Still Water 1lt', 'Still water 1 litre', 3.50, array['ουδέτερο', 'βασικό']::text[], 85),
    ('DR002', 'Soft Drinks', 'S.Pellegrino 750ml', 'Sparkling mineral water 750ml', 6.00, array['αφρώδες', 'δροσερό']::text[], 86),
    ('DR003', 'Soft Drinks', 'Three Cents Pink Grapefruit Soda', 'Pink grapefruit soda 200ml', 4.00, array['εσπεριδοειδές', 'αφρώδες', 'δροσερό', 'φρουτώδες']::text[], 87),
    ('DR004', 'Soft Drinks', 'Espresso', 'Espresso coffee', 3.00, array['καφέ', 'έντονο', 'ζεστό']::text[], 88),
    ('DR005', 'Soft Drinks', 'Tea', 'Tea', 3.00, array['ελαφρύ', 'ζεστό', 'αρωματικό']::text[], 89),
    ('CI001', 'Ciders', 'Milokleftis Greek Apple Cider', 'Greek apple cider, 330ml, 4.5% alc.', 6.00, array['φρουτώδες', 'γλυκό', 'ελληνικό', 'αφρώδες']::text[], 90),
    ('CI002', 'Ciders', 'Strongbow Red Berries', 'Cider with red berries, 330ml, 4.5% alc.', 6.00, array['φρουτώδες', 'γλυκό', 'αφρώδες', 'μούρα']::text[], 91),
    ('BE001', 'Beers', 'Heineken Draft', 'Lager, 400ml, 5% alc.', 6.00, array['δροσερό', 'ελαφρύ', 'κλασικό']::text[], 92),
    ('BE002', 'Beers', 'Alfa Lager', 'Greek lager, 330ml, 5% alc.', 5.00, array['δροσερό', 'ελαφρύ', 'ελληνικό', 'κλασικό']::text[], 93),
    ('BE003', 'Beers', 'Amstel Radler', 'Lemon radler, 330ml, 4.2% alc.', 5.00, array['εσπεριδοειδές', 'δροσερό', 'ελαφρύ', 'φρουτώδες']::text[], 94),
    ('BE004', 'Beers', 'Mamos Pilsner', 'Pilsner, 330ml, 5% alc.', 5.00, array['δροσερό', 'ελαφρύ', 'πικρό']::text[], 95),
    ('BE005', 'Beers', 'Erdinger Weiss', 'Wheat beer, 330ml, 5.3% alc.', 6.00, array['σιταρένιο', 'αφρώδες', 'αρωματικό', 'φρουτώδες']::text[], 96),
    ('BE006', 'Beers', 'Sol Exotic Lager', 'Exotic lager, 330ml, 4.2% alc.', 6.00, array['ελαφρύ', 'δροσερό', 'τροπικό']::text[], 97),
    ('BE007', 'Beers', 'Asahi Dry Japanese Beer', 'Dry Japanese beer, 330ml', 9.00, array['ξηρό', 'ελαφρύ', 'ιαπωνικό', 'καθαρό']::text[], 98),
    ('WH001', 'Whiskey', 'Johnnie Walker Red Label', 'Blended Scotch Whisky', 10.00, array['καπνιστό', 'δυνατό', 'κλασικό']::text[], 99),
    ('WH002', 'Whiskey', 'Johnnie Walker Black Label', 'Blended Scotch Whisky, 12 years', 11.00, array['καπνιστό', 'δυνατό', 'βαθύ άρωμα', 'πλούσιο']::text[], 100),
    ('WH003', 'Whiskey', 'Dewar''s', 'Blended Scotch Whisky', 10.00, array['ελαφρύ', 'γλυκό', 'κλασικό']::text[], 101),
    ('WH004', 'Whiskey', 'Metaxa 5 Stars', 'Greek aged spirit', 10.00, array['ελληνικό', 'γλυκό', 'αρωματικό', 'βαθύ γεύση']::text[], 102),
    ('WW001', 'White Wines', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · glass: €7', 32.00, array['δροσερό', 'εσπεριδοειδές', 'ξηρό', 'ελαφρύ', 'ελληνικό']::text[], 103),
    ('WW002', 'White Wines', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Muscat · glass: €7', 30.00, array['αρωματικό', 'φρουτώδες', 'ελαφρύ', 'ελληνικό']::text[], 104),
    ('WW003', 'White Wines', 'Propodes | Domaine Zafeirakis', 'Chardonnay', 40.00, array['βουτυράτο', 'πλούσιο', 'ξηρό', 'κλασικό']::text[], 105),
    ('WW004', 'White Wines', 'Megathiri | Tatakis Wines', 'Athiri', 34.00, array['ελαφρύ', 'εσπεριδοειδές', 'ξηρό', 'ελληνικό']::text[], 106),
    ('WW005', 'White Wines', 'Theros Wine Collectiva', 'Thrapsathiri', 45.00, array['αρωματικό', 'ελαφρύ', 'ελληνικό', 'νησιώτικο']::text[], 107),
    ('WW006', 'White Wines', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko', 35.00, array['αρωματικό', 'φρουτώδες', 'ξηρό', 'ελληνικό']::text[], 108),
    ('WW007', 'White Wines', 'Akrathos Newlands Winery', 'Assyrtiko', 45.00, array['ξηρό', 'μεταλλικό', 'εσπεριδοειδές', 'ελληνικό']::text[], 109),
    ('WW008', 'White Wines', 'Domaine Costa Lazaridi', 'Semillon', 40.00, array['κρεμώδες', 'πλούσιο', 'ξηρό']::text[], 110),
    ('WW009', 'White Wines', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc', 36.00, array['αρωματικό', 'δροσερό', 'εσπεριδοειδές', 'ξηρό']::text[], 111),
    ('WW010', 'White Wines', 'Weingut Thorle', 'Riesling off dry', 37.00, array['ημίξηρο', 'εσπεριδοειδές', 'λουλουδάτο', 'ελαφρύ']::text[], 112),
    ('WW011', 'White Wines', 'Bourgogne / Domaine David Moret', 'Chardonnay', 60.00, array['πολυτελές', 'βουτυράτο', 'πλούσιο', 'κλασικό']::text[], 113),
    ('RO001', 'Rose Wines', '4-6H | Gaia Wines', 'Agiorgitiko rosé · glass: €7', 30.00, array['φρουτώδες', 'δροσερό', 'ελαφρύ', 'ελληνικό']::text[], 114),
    ('RO002', 'Rose Wines', 'Joker Semi Dry | Liappis Boutique Winery', 'Muscat, Syrah rosé · glass: €7', 30.00, array['ημίξηρο', 'αρωματικό', 'φρουτώδες', 'γλυκό']::text[], 115),
    ('RO003', 'Rose Wines', 'Maissa | Tatakis Wines', 'Syrah, Merlot rosé', 34.00, array['φρουτώδες', 'ξηρό', 'ελαφρύ', 'ελληνικό']::text[], 116),
    ('RO004', 'Rose Wines', 'Techni Alipias | Wine Art Estate', 'Syrah rosé', 35.00, array['φρουτώδες', 'ξηρό', 'ελαφρύ', 'ελληνικό']::text[], 117),
    ('RO005', 'Rose Wines', 'Domaine Costa Lazaridi Rose', 'Merlot, Agiorgitiko, Syrah rosé', 36.00, array['φρουτώδες', 'ξηρό', 'γεμάτο', 'ελληνικό']::text[], 118),
    ('RO006', 'Rose Wines', 'Alpha Estate', 'Xinomavro rosé', 42.00, array['ξηρό', 'φρουτώδες', 'επίμονο', 'ελληνικό']::text[], 119),
    ('RO007', 'Rose Wines', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah rosé', 60.00, array['πολυτελές', 'φρουτώδες', 'ξηρό', 'γαλλικό']::text[], 120),
    ('RO008', 'Rose Wines', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourvèdre, Rolle rosé', 70.00, array['πολυτελές', 'ξηρό', 'φρουτώδες', 'γαλλικό', 'Προβηγκία']::text[], 121),
    ('RE001', 'Red Wines', 'Kompsos | Karavitakis Winery', 'Liatiko red · glass: €7', 30.00, array['φρουτώδες', 'ελαφρύ', 'νησιώτικο', 'ελληνικό']::text[], 122),
    ('RE002', 'Red Wines', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot red', 40.00, array['γεμάτο', 'φρουτώδες', 'γήινο', 'ελληνικό']::text[], 123),
    ('RE003', 'Red Wines', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot', 39.00, array['δυνατό', 'γεμάτο', 'τανικό', 'πολύπλοκο']::text[], 124),
    ('SP001', 'Champagne & Sparkling', 'Martini Prosecco D.O.C', 'Prosecco · glass: €8', 35.00, array['αφρώδες', 'ελαφρύ', 'δροσερό', 'φρουτώδες']::text[], 125),
    ('SP002', 'Champagne & Sparkling', 'Martini Asti Semi Sweet', 'Semi-sweet sparkling wine · glass: €8', 35.00, array['αφρώδες', 'ημίγλυκο', 'φρουτώδες', 'ελαφρύ']::text[], 126),
    ('SP003', 'Champagne & Sparkling', 'Moet & Chandon Ice Imperial', 'Champagne served over ice', 180.00, array['πολυτελές', 'αφρώδες', 'δροσερό', 'φρουτώδες']::text[], 127),
    ('SP004', 'Champagne & Sparkling', 'Moet & Chandon Rose Imperial Brut', 'Rosé Champagne Brut', 160.00, array['πολυτελές', 'αφρώδες', 'φρουτώδες', 'ξηρό']::text[], 128),
    ('SP005', 'Champagne & Sparkling', 'Louis Roederer Brut Collection', 'Champagne Brut Collection', 170.00, array['πολυτελές', 'αφρώδες', 'ξηρό', 'πολύπλοκο']::text[], 129),
    ('SH001', 'Shisha', 'Shisha', 'Available flavors: Blue ice, Forest pulp (strawberry, berry), Alter ego (berry, mango, mint), Knock out (passion fruit, mango), Watermelon, Peach, Lemon mint, Two apples (green, red)', 20.00, array['φρουτώδες', 'αρωματικό', 'lounge', 'κοινωνικό']::text[], 130)
) as v(external_id, category_name, name, description, price, tags, display_order)
join menu_categories c on c.name = v.category_name
on conflict (external_id) where external_id is not null do update
set
    category_id = excluded.category_id,
    name = excluded.name,
    description = excluded.description,
    price = excluded.price,
    tags = excluded.tags,
    is_available = excluded.is_available,
    display_order = excluded.display_order;

insert into menu_item_translations (menu_item_id, language_code, name, description)
select mi.id, v.language_code, v.name, v.description
from (
    values
    ('UR001', 'el', 'Cucumber Maki', 'αγγούρι'),
    ('UR001', 'en', 'Cucumber Maki', 'cucumber'),
    ('UR001', 'de', 'Gurken Maki', 'Gurke'),
    ('UR001', 'it', 'Cucumber Maki', 'cetriolo'),
    ('UR001', 'sv', 'Gurk Maki', 'gurka'),
    ('UR002', 'el', 'Avocado Maki', 'αβοκάντο'),
    ('UR002', 'en', 'Avocado Maki', 'avocado'),
    ('UR002', 'de', 'Avocado Maki', 'Avocado'),
    ('UR002', 'it', 'Avocado Maki', 'avocado'),
    ('UR002', 'sv', 'Avokado Maki', 'avokado'),
    ('UR003', 'el', 'Veggie Roll', 'αγγούρι, αβοκάντο, μάνγκο, κρεμμυδάκι φρέσκο, philadelphia, πράσινο αυγοτάραχο'),
    ('UR003', 'en', 'Veggie Roll', 'cucumber, avocado, mango, spring onion, cream cheese, green tobico'),
    ('UR003', 'de', 'Veggie Roll', 'Gurke, Avocado, Mango, Frühlingszwiebel, Frischkäse, grüner Tobiko'),
    ('UR003', 'it', 'Veggie Roll', 'cetriolo, avocado, mango, cipollotto, formaggio spalmabile, tobico verde'),
    ('UR003', 'sv', 'Veggie Roll', 'gurka, avokado, mango, salladslök, färskost, grön tobiko'),
    ('UR004', 'el', 'Vegan Roll', 'αγγούρι, αβοκάντο, μάνγκο, κρεμμυδάκι φρέσκο, vegan μαγιονέζα, σουσάμι'),
    ('UR004', 'en', 'Vegan Roll', 'cucumber, avocado, mango, spring onion, vegan mayo, sesame'),
    ('UR004', 'de', 'Vegan Roll', 'Gurke, Avocado, Mango, Frühlingszwiebel, vegane Mayo, Sesam'),
    ('UR004', 'it', 'Vegan Roll', 'cetriolo, avocado, mango, cipollotto, maionese vegana, sesamo'),
    ('UR004', 'sv', 'Vegan Roll', 'gurka, avokado, mango, salladslök, vegansk majonnäs, sesam'),
    ('UR005', 'el', 'California Salmon', 'σολομός, αγγούρι, τυρί κρέμα Philadelphia, σουσάμι'),
    ('UR005', 'en', 'California Salmon', 'salmon, cucumber, avocado, cream cheese, sesame'),
    ('UR005', 'de', 'California Salmon', 'Lachs, Gurke, Avocado, Frischkäse, Sesam'),
    ('UR005', 'it', 'California Salmon', 'salmone, cetriolo, avocado, formaggio spalmabile, sesamo'),
    ('UR005', 'sv', 'California Salmon', 'lax, gurka, avokado, färskost, sesam'),
    ('UR006', 'el', 'California Crab', 'καβούρι, αγγούρι, αβοκάντο, τυρί κρέμα, μαγιονέζα, σουσάμι'),
    ('UR006', 'en', 'California Crab', 'crab kanimi, cucumber, avocado, cream mayo, sesame'),
    ('UR006', 'de', 'California Crab', 'Krabben-Kanimi, Gurke, Avocado, Crème Mayo, Sesam'),
    ('UR006', 'it', 'California Crab', 'granchio kanimi, cetriolo, avocado, maionese cremosa, sesamo'),
    ('UR006', 'sv', 'California Crab', 'krabb kanimi, gurka, avokado, krämig majonnäs, sesam'),
    ('UR007', 'el', 'Shrimp Tempura', 'γαρίδες τεμπούρα, αβοκάντο, πικάντικη μαγιονέζα, κόκκινο αυγοτάραχο'),
    ('UR007', 'en', 'Shrimp Tempura', 'shrimp tempura, avocado, spicy mayo, red masago'),
    ('UR007', 'de', 'Garnelen Tempura', 'Garnelen-Tempura, Avocado, scharfe Mayo, roter Masago'),
    ('UR007', 'it', 'Gamberi Tempura', 'gamberi in tempura, avocado, maionese piccante, masago rosso'),
    ('UR007', 'sv', 'Räkor Tempura', 'räkor i tempura, avokado, stark majonnäs, röd masago'),
    ('UR008', 'el', 'Tekka Kimchi', 'τόνος, αγγούρι, τηγανητό σκόρδο, μαγιονέζα με κίμτσι, σουσάμι με κίμτσι'),
    ('UR008', 'en', 'Tekka Kimchi', 'tuna, cucumber, fried garlic, kimchi mayo, kimchi sesame'),
    ('UR008', 'de', 'Tekka Kimchi', 'Thunfisch, Gurke, gebratener Knoblauch, Kimchi-Mayo, Kimchi-Sesam'),
    ('UR008', 'it', 'Tekka Kimchi', 'tonno, cetriolo, aglio fritto, maionese kimchi, sesamo kimchi'),
    ('UR008', 'sv', 'Tekka Kimchi', 'tonfisk, gurka, stekt vitlök, kimchi majonnäs, kimchi sesam'),
    ('UR009', 'el', 'Spicy Suzuki', 'λαβράκι, αγγούρι, αβοκάντο, μαγιονέζα με τσίλι, αυγοτάραχο με yuzu'),
    ('UR009', 'en', 'Spicy Suzuki', 'sea bass, cucumber, avocado, chilli mayo, yuzu, tobico'),
    ('UR009', 'de', 'Spicy Suzuki', 'Wolfsbarsch, Gurke, Avocado, Chili-Mayo, Yuzu, Tobiko'),
    ('UR009', 'it', 'Spicy Suzuki', 'branzino, cetriolo, avocado, maionese al peperoncino, yuzu, tobico'),
    ('UR009', 'sv', 'Spicy Suzuki', 'havsabborre, gurka, avokado, chilimajonnäs, yuzu, tobiko'),
    ('NI001', 'el', 'Avocado Nigiri', 'Αβοκάντο'),
    ('NI001', 'en', 'Avocado Nigiri', 'avocado'),
    ('NI001', 'de', 'Avocado Nigiri', 'Avocado'),
    ('NI001', 'it', 'Nigiri Avocado', 'avocado'),
    ('NI001', 'sv', 'Avokado Nigiri', 'avokado'),
    ('NI002', 'el', 'Salmon Nigiri', 'Σολομός'),
    ('NI002', 'en', 'Salmon Nigiri', 'salmon'),
    ('NI002', 'de', 'Lachs Nigiri', 'Lachs'),
    ('NI002', 'it', 'Nigiri Salmone', 'salmone'),
    ('NI002', 'sv', 'Lax Nigiri', 'lax'),
    ('NI003', 'el', 'Tuna Nigiri', 'Τόνος'),
    ('NI003', 'en', 'Tuna Nigiri', 'tuna'),
    ('NI003', 'de', 'Thunfisch Nigiri', 'Thunfisch'),
    ('NI003', 'it', 'Nigiri Tonno', 'tonno'),
    ('NI003', 'sv', 'Tonfisk Nigiri', 'tonfisk'),
    ('NI004', 'el', 'Sea Bass Nigiri', 'Λαβράκι'),
    ('NI004', 'en', 'Sea Bass Nigiri', 'sea bass'),
    ('NI004', 'de', 'Wolfsbarsch Nigiri', 'Wolfsbarsch'),
    ('NI004', 'it', 'Nigiri Branzino', 'branzino'),
    ('NI004', 'sv', 'Havsabborre Nigiri', 'havsabborre'),
    ('NI005', 'el', 'Shrimp Nigiri', 'Γαρίδα'),
    ('NI005', 'en', 'Shrimp Nigiri', 'shrimp'),
    ('NI005', 'de', 'Garnelen Nigiri', 'Garnele'),
    ('NI005', 'it', 'Nigiri Gambero', 'gambero'),
    ('NI005', 'sv', 'Räk Nigiri', 'räka'),
    ('NI006', 'el', 'Smoked Eel Nigiri', 'Καπνιστό Χέλι'),
    ('NI006', 'en', 'Smoked Eel Nigiri', 'smoked eel'),
    ('NI006', 'de', 'Geräucherter Aal Nigiri', 'geräucherter Aal'),
    ('NI006', 'it', 'Nigiri Anguilla Affumicata', 'anguilla affumicata'),
    ('NI006', 'sv', 'Rökt Ål Nigiri', 'rökt ål'),
    ('SR001', 'el', 'Mango Mango', 'Μέσα: γαρίδα τεμπούρα, cream cheese. Έξω: μάνγκο, passion fruit μαγιονέζα, σουσάμι, σχοινόπρασο'),
    ('SR001', 'en', 'Mango Mango', 'Inside: shrimp tempura, cream cheese. On top: mango, passion fruit mayo, sesame, chives'),
    ('SR001', 'de', 'Mango Mango', 'Innen: Garnelen-Tempura, Frischkäse. Oben: Mango, Passionsfrucht-Mayo, Sesam, Schnittlauch'),
    ('SR001', 'it', 'Mango Mango', 'Dentro: gamberi tempura, formaggio spalmabile. Sopra: mango, maionese al frutto della passione, sesamo, erba cipollina'),
    ('SR001', 'sv', 'Mango Mango', 'Inuti: räkor tempura, färskost. Ovanpå: mango, passionsfrukts majonnäs, sesam, gräslök'),
    ('SR002', 'el', 'Crab & Tuna', 'Μέσα: τόνος, αβοκάντο, αγγούρι, κρεμμύδι φρέσκο. Έξω: καβούρι, πικάντικη μαγιονέζα, σχοινόπρασο, τραγανό κρεμμύδι'),
    ('SR002', 'en', 'Crab & Tuna', 'Inside: tuna, avocado, cucumber, spring onion. On top: crab, spicy mayo, chives, crispy onion'),
    ('SR002', 'de', 'Krabbe & Thunfisch', 'Innen: Thunfisch, Avocado, Gurke, Frühlingszwiebel. Oben: Krabbe, scharfe Mayo, Schnittlauch, knusprige Zwiebeln'),
    ('SR002', 'it', 'Granchio & Tonno', 'Dentro: tonno, avocado, cetriolo, cipollotto. Sopra: granchio, maionese piccante, erba cipollina, cipolla croccante'),
    ('SR002', 'sv', 'Krabba & Tonfisk', 'Inuti: tonfisk, avokado, gurka, salladslök. Ovanpå: krabba, stark majonnäs, gräslök, krispig lök'),
    ('SR003', 'el', 'Spicy Tuna', 'Μέσα: τόνος, αβοκάντο, αγγούρι. Έξω: σασίμι τόνου, καυτερή μαγιονέζα, τογκαράσι, σχοινόπρασο'),
    ('SR003', 'en', 'Spicy Tuna', 'Inside: tuna, avocado, cucumber. On top: tuna sashimi, spicy mayo, togarashi, chives'),
    ('SR003', 'de', 'Schärfer Thunfisch', 'Innen: Thunfisch, Avocado, Gurke. Oben: Thunfisch-Sashimi, scharfe Mayo, Togarashi, Schnittlauch'),
    ('SR003', 'it', 'Tonno Piccante', 'Dentro: tonno, avocado, cetriolo. Sopra: sashimi di tonno, maionese piccante, togarashi, erba cipollina'),
    ('SR003', 'sv', 'Stark Tonfisk', 'Inuti: tonfisk, avokado, gurka. Ovanpå: tonfisk sashimi, stark majonnäs, togarashi, gräslök'),
    ('SR004', 'el', 'Salmon Truffle', 'Μέσα: σολομός, αγγούρι, κρεμμύδι φρέσκο. Έξω: ψημένος σολομός, unagi σως, μαγιονέζα τρούφας, τραγανό σκόρδο, χαβιάρι'),
    ('SR004', 'en', 'Salmon Truffle', 'Inside: salmon, cucumber, spring onion. On top: seared salmon, unagi sauce, truffle mayo, crispy garlic, caviar'),
    ('SR004', 'de', 'Lachs Trüffel', 'Innen: Lachs, Gurke, Frühlingszwiebel. Oben: angebratener Lachs, Unagi-Sauce, Trüffel-Mayo, knuspriger Knoblauch, Kaviar'),
    ('SR004', 'it', 'Salmone al Tartufo', 'Dentro: salmone, cetriolo, cipollotto. Sopra: salmone scottato, salsa unagi, maionese al tartufo, aglio croccante, caviale'),
    ('SR004', 'sv', 'Lax Tryffel', 'Inuti: lax, gurka, salladslök. Ovanpå: stekt lax, unagi sås, tryffel majonnäs, krispig vitlök, kaviar'),
    ('SR005', 'el', 'Phili Salmon', 'Μέσα: σολομός, τυρί κρέμα Philadelphia, μάνγκο. Έξω: ταρτάρ σολομού, μαγιονέζα γλυκό τσίλι, ικούρα, κρεμμύδι φρέσκο'),
    ('SR005', 'en', 'Phili Salmon', 'Inside: salmon, cream cheese, mango. On top: salmon tartare, sweet chili mayo, ikura, spring onions'),
    ('SR005', 'de', 'Phili Lachs', 'Innen: Lachs, Frischkäse, Mango. Oben: Lachs-Tatar, süße Chili-Mayo, Ikura, Frühlingszwiebeln'),
    ('SR005', 'it', 'Phili Salmone', 'Dentro: salmone, formaggio spalmabile, mango. Sopra: tartare di salmone, maionese dolce al peperoncino, ikura, cipollotti'),
    ('SR005', 'sv', 'Phili Lax', 'Inuti: lax, färskost, mango. Ovanpå: lax tartar, söt chili majonnäs, ikura, salladslök'),
    ('SR006', 'el', 'Suzuki & Shrimp', 'Μέσα: γαρίδα τεμπούρα, τυρί κρέμα Philadelphia, μάνγκο. Έξω: λαυράκι, γλυκιά πικάντικη μαγιονέζα, τεριγιάκι, κρεμμυδάκι φρέσκο, tobico'),
    ('SR006', 'en', 'Suzuki & Shrimp', 'Inside: shrimp tempura, cream cheese, mango. On top: seared sea bass, sweet spicy mayo, teriyaki, spring onions, tobico'),
    ('SR006', 'de', 'Suzuki & Garnelen', 'Innen: Garnelen-Tempura, Frischkäse, Mango. Oben: angebratener Wolfsbarsch, süß-scharfe Mayo, Teriyaki, Frühlingszwiebeln, Tobiko'),
    ('SR006', 'it', 'Suzuki & Gamberi', 'Dentro: gamberi tempura, formaggio spalmabile, mango. Sopra: branzino scottato, maionese dolce piccante, teriyaki, cipollotti, tobico'),
    ('SR006', 'sv', 'Suzuki & Räkor', 'Inuti: räkor tempura, färskost, mango. Ovanpå: stekt havsabborre, sötstark majonnäs, teriyaki, salladslök, tobiko'),
    ('SR007', 'el', 'Crispy Shrimp', 'Μέσα: γαρίδα τεμπούρα, κρεμμυδάκι φρέσκο, τυρί κρέμα philadelphia. Έξω: αβοκάντο, πικάντικη μαγιονέζα, τραγανό κρεμμύδι, σχοινόπρασο'),
    ('SR007', 'en', 'Crispy Shrimp', 'Inside: shrimp tempura, spring onion, cream cheese. On top: avocado, spicy mayo, crispy onion, chives'),
    ('SR007', 'de', 'Knusprige Garnelen', 'Innen: Garnelen-Tempura, Frühlingszwiebel, Frischkäse. Oben: Avocado, scharfe Mayo, knusprige Zwiebeln, Schnittlauch'),
    ('SR007', 'it', 'Gamberi Croccanti', 'Dentro: gamberi tempura, cipollotto, formaggio spalmabile. Sopra: avocado, maionese piccante, cipolla croccante, erba cipollina'),
    ('SR007', 'sv', 'Krispiga Räkor', 'Inuti: räkor tempura, salladslök, färskost. Ovanpå: avokado, stark majonnäs, krispig lök, gräslök'),
    ('SR008', 'el', 'Chicken Roll', 'Μέσα: τραγανό κοτόπουλο, μαρούλι iceberg, κρεμμυδάκι φρέσκο. Έξω: αβοκάντο, τραγανό κρεμμύδι, μαγιονέζα hoisin'),
    ('SR008', 'en', 'Chicken Roll', 'Inside: crispy chicken, iceberg lettuce, spring onion. On top: avocado, crispy onion, hoisin mayo'),
    ('SR008', 'de', 'Hühner Roll', 'Innen: knuspriges Hähnchen, Eisbergsalat, Frühlingszwiebel. Oben: Avocado, knusprige Zwiebeln, Hoisin-Mayo'),
    ('SR008', 'it', 'Roll di Pollo', 'Dentro: pollo croccante, lattuga iceberg, cipollotto. Sopra: avocado, cipolla croccante, maionese hoisin'),
    ('SR008', 'sv', 'Kyckling Roll', 'Inuti: krispig kyckling, isbergssallad, salladslök. Ovanpå: avokado, krispig lök, hoisin majonnäs'),
    ('SR009', 'el', 'Masao', 'Μέσα: γαρίδα τεμπούρα, αβοκάντο, κρεμμύδι φρέσκο. Έξω: μοσχάρι ταρτάρ, μαγιονέζα τρούφας, τραγανό κρεμμύδι, σχοινόπρασο'),
    ('SR009', 'en', 'Masao', 'Inside: shrimp tempura, avocado, spring onion. On top: beef tartare, truffle mayo, crispy onion, chives'),
    ('SR009', 'de', 'Masao', 'Innen: Garnelen-Tempura, Avocado, Frühlingszwiebel. Oben: Rindertatar, Trüffel-Mayo, knusprige Zwiebeln, Schnittlauch'),
    ('SR009', 'it', 'Masao', 'Dentro: gamberi tempura, avocado, cipollotto. Sopra: tartare di manzo, maionese al tartufo, cipolla croccante, erba cipollina'),
    ('SR009', 'sv', 'Masao', 'Inuti: räkor tempura, avokado, salladslök. Ovanpå: nöttartar, tryffel majonnäs, krispig lök, gräslök'),
    ('SR010', 'el', 'Aegean Roll', 'Μέσα: αγγούρι, αβοκάντο, φέτα. Έξω: σοταρισμένο λαβράκι, μαγιονέζα λάιμ, ελαιόλαδο, άνηθος, σουσάμι'),
    ('SR010', 'en', 'Aegean Roll', 'Inside: cucumber, avocado, feta cheese. On top: seared sea bass, lime mayo, olive oil, dill, sesame'),
    ('SR010', 'de', 'Ägäischer Roll', 'Innen: Gurke, Avocado, Feta-Käse. Oben: angebratener Wolfsbarsch, Limetten-Mayo, Olivenöl, Dill, Sesam'),
    ('SR010', 'it', 'Aegean Roll', 'Dentro: cetriolo, avocado, formaggio feta. Sopra: branzino scottato, maionese al lime, olio d''oliva, aneto, sesamo'),
    ('SR010', 'sv', 'Aegean Roll', 'Inuti: gurka, avokado, fetaost. Ovanpå: stekt havsabborre, lime majonnäs, olivolja, dill, sesam'),
    ('RAW001', 'el', 'Sea Bass Carpaccio', 'λαβράκι, εσπεριδοειδή, κόκκινη πιπεριά, yuzu, chili, ελαιόλαδο, λεμόνι, άνηθος'),
    ('RAW001', 'en', 'Sea Bass Carpaccio', 'sea bass, citrus, red pepper, yuzu, chilli, olive oil, lemon, dill'),
    ('RAW001', 'de', 'Wolfsbarsch Carpaccio', 'Wolfsbarsch, Zitrusfrüchte, rote Paprika, Yuzu, Chili, Olivenöl, Zitrone, Dill'),
    ('RAW001', 'it', 'Carpaccio di Branzino', 'branzino, agrumi, peperone rosso, yuzu, peperoncino, olio d''oliva, limone, aneto'),
    ('RAW001', 'sv', 'Havsabborre Carpaccio', 'havsabborre, citrus, röd paprika, yuzu, chili, olivolja, citron, dill'),
    ('RAW002', 'el', 'Salmon Yuzu', 'σολομός, ikura, ξύσμα λάιμ, φρέσκο κρεμμυδάκι, μάνγκο, yuzu, σουσάμι'),
    ('RAW002', 'en', 'Salmon Yuzu', 'salmon, ikura, lime zest, spring onion, mango, yuzu, sesame'),
    ('RAW002', 'de', 'Lachs Yuzu', 'Lachs, Ikura, Limettenschale, Frühlingszwiebel, Mango, Yuzu, Sesam'),
    ('RAW002', 'it', 'Salmone Yuzu', 'salmone, ikura, scorza di lime, cipollotto, mango, yuzu, sesamo'),
    ('RAW002', 'sv', 'Lax Yuzu', 'lax, ikura, limeskal, salladslök, mango, yuzu, sesam'),
    ('RAW003', 'el', 'Tuna Turf', 'τόνος, λάδι τρούφας, τοματίνια, μαΐντανος, φρέσκο κρεμμυδάκι'),
    ('RAW003', 'en', 'Tuna Turf', 'tuna, truffle oil, cherry tomato, parsley, spring onion'),
    ('RAW003', 'de', 'Thunfisch Turf', 'Thunfisch, Trüffelöl, Kirschtomaten, Petersilie, Frühlingszwiebel'),
    ('RAW003', 'it', 'Tonno Turf', 'tonno, olio al tartufo, pomodorini, prezzemolo, cipollotto'),
    ('RAW003', 'sv', 'Tonfisk Turf', 'tonfisk, tryffelolja, körsbärstomater, persilja, salladslök'),
    ('RAW004', 'el', 'Variety of Sashimi 12pcs', 'σολομός, τόνος, λαβράκι'),
    ('RAW004', 'en', 'Variety of Sashimi 12pcs', 'salmon, tuna, sea bass'),
    ('RAW004', 'de', 'Sashimi Auswahl 12 Stück', 'Lachs, Thunfisch, Wolfsbarsch'),
    ('RAW004', 'it', 'Selezione di Sashimi 12 pezzi', 'salmone, tonno, branzino'),
    ('RAW004', 'sv', 'Sashimi Urval 12 bitar', 'lax, tonfisk, havsabborre'),
    ('CF001', 'el', 'Crispy Tekka Roll', 'Μέσα: τόνος, αγγούρι, τυρί κρέμα. Έξω: πικάντικη μαγιονέζα, τεριγιάκι, σχοινόπρασο'),
    ('CF001', 'en', 'Crispy Tekka Roll', 'Inside: tuna, cucumber, cream cheese. On top: spicy mayo, teriyaki, chives'),
    ('CF001', 'de', 'Knuspriger Tekka Roll', 'Innen: Thunfisch, Gurke, Frischkäse. Oben: scharfe Mayo, Teriyaki, Schnittlauch'),
    ('CF001', 'it', 'Crispy Tekka Roll', 'Dentro: tonno, cetriolo, formaggio spalmabile. Sopra: maionese piccante, teriyaki, erba cipollina'),
    ('CF001', 'sv', 'Krispig Tekka Roll', 'Inuti: tonfisk, gurka, färskost. Ovanpå: stark majonnäs, teriyaki, gräslök'),
    ('CF002', 'el', 'Crunchy Salmon Roll', 'Μέσα: σολομός, τυρί κρέμα Philadelphia, αβοκάντο. Έξω: μαγιονέζα hoisin, σχοινόπρασο'),
    ('CF002', 'en', 'Crunchy Salmon Roll', 'Inside: salmon, cream cheese, avocado. On top: hoisin mayo, chives'),
    ('CF002', 'de', 'Knuspriger Lachsroll', 'Innen: Lachs, Frischkäse, Avocado. Oben: Hoisin-Mayo, Schnittlauch'),
    ('CF002', 'it', 'Crunchy Salmon Roll', 'Dentro: salmone, formaggio spalmabile, avocado. Sopra: maionese hoisin, erba cipollina'),
    ('CF002', 'sv', 'Krispig Laxrulle', 'Inuti: lax, färskost, avokado. Ovanpå: hoisin majonnäs, gräslök'),
    ('CF003', 'el', 'Crispy Veggie Roll', 'Μέσα: αγγούρι, τυρί κρέμα Philadelphia, αβοκάντο. Έξω: μαγιονέζα hoisin, σχοινόπρασο'),
    ('CF003', 'en', 'Crispy Veggie Roll', 'Inside: cucumber, cream cheese, avocado. On top: hoisin mayo, chives'),
    ('CF003', 'de', 'Knuspriger Gemüse Roll', 'Innen: Gurke, Frischkäse, Avocado. Oben: Hoisin-Mayo, Schnittlauch'),
    ('CF003', 'it', 'Crispy Veggie Roll', 'Dentro: cetriolo, formaggio spalmabile, avocado. Sopra: maionese hoisin, erba cipollina'),
    ('CF003', 'sv', 'Krispig Veggie Roll', 'Inuti: gurka, färskost, avokado. Ovanpå: hoisin majonnäs, gräslök'),
    ('BI001', 'el', 'Chicken Dumplings', 'σάλτσα ponzu τρούφας, φρέσκο κρεμμύδι'),
    ('BI001', 'en', 'Chicken Dumplings', 'truffle ponzu sauce, spring onion'),
    ('BI001', 'de', 'Hühnchen Dumplings', 'Trüffel-Ponzu-Sauce, Frühlingszwiebel'),
    ('BI001', 'it', 'Ravioli di Pollo', 'salsa ponzu al tartufo, cipollotto'),
    ('BI001', 'sv', 'Kycklingdumplings', 'tryffel ponzu sås, salladslök'),
    ('BI002', 'el', 'Spring Rolls', 'ρολά λαχανικών, γλυκιά σάλτσα τσίλι'),
    ('BI002', 'en', 'Spring Rolls', 'vegetable spring rolls, sweet chilli sauce'),
    ('BI002', 'de', 'Frühlingsrollen', 'Gemüse-Frühlingsrollen, süße Chili-Sauce'),
    ('BI002', 'it', 'Involtini Primavera', 'involtini di verdure, salsa dolce al peperoncino'),
    ('BI002', 'sv', 'Vårrullar', 'grönsaks vårrullar, söt chilisås'),
    ('BI003', 'el', 'Shrimp Gyoza', 'σάλτσα σόγια τσίλι, σχοινόπρασο'),
    ('BI003', 'en', 'Shrimp Gyoza', 'chilli soy sauce, chives'),
    ('BI003', 'de', 'Garnelen Gyoza', 'Chili-Sojasoße, Schnittlauch'),
    ('BI003', 'it', 'Gyoza di Gamberi', 'salsa di soia piccante, erba cipollina'),
    ('BI003', 'sv', 'Räk Gyoza', 'chili sojasås, gräslök'),
    ('BI004', 'el', 'Crispy Cheese Wonton', 'Wonton με γαρίδα, καβούρι και τυρί κρέμα'),
    ('BI004', 'en', 'Crispy Cheese Wonton', 'shrimp, crab, cream cheese'),
    ('BI004', 'de', 'Knusprige Käse Wonton', 'Garnelen, Krabben, Frischkäse'),
    ('BI004', 'it', 'Wonton Croccante al Formaggio', 'gamberi, granchio, formaggio spalmabile'),
    ('BI004', 'sv', 'Krispiga Ost Wonton', 'räkor, krabba, färskost'),
    ('BAO001', 'el', 'Shrimp Bao', 'γαρίδες τεμπούρα, αγγούρι, κρέμα αβοκάντο, μαρούλι, πικάντικο σχοινόπρασο, σουσάμι'),
    ('BAO001', 'en', 'Shrimp Bao', 'shrimp tempura, cucumber, avocado cream, lettuce, spicy mayo, chives, sesame'),
    ('BAO001', 'de', 'Garnelen Bao', 'Garnelen-Tempura, Gurke, Avocado-Creme, Salat, scharfe Mayo, Schnittlauch, Sesam'),
    ('BAO001', 'it', 'Bao ai Gamberi', 'gamberi tempura, cetriolo, crema di avocado, lattuga, maionese piccante, erba cipollina, sesamo'),
    ('BAO001', 'sv', 'Räk Bao', 'räkor tempura, gurka, avokadokräm, sallad, stark majonnäs, gräslök, sesam'),
    ('BAO002', 'el', 'Chicken Bao', 'τραγανό κοτόπουλο, αγγούρι, κρέμα αβοκάντο, μαρούλι, πικάντικο σχοινόπρασο, τραγανό κρεμμύδι'),
    ('BAO002', 'en', 'Chicken Bao', 'crispy chicken, cucumber, avocado cream, lettuce, spicy mayo, chives, crispy onion'),
    ('BAO002', 'de', 'Hühnchen Bao', 'knuspriges Hähnchen, Gurke, Avocado-Creme, Salat, scharfe Mayo, Schnittlauch, knusprige Zwiebeln'),
    ('BAO002', 'it', 'Bao al Pollo', 'pollo croccante, cetriolo, crema di avocado, lattuga, maionese piccante, erba cipollina, cipolla croccante'),
    ('BAO002', 'sv', 'Kyckling Bao', 'krispig kyckling, gurka, avokadokräm, sallad, stark majonnäs, gräslök, krispig lök'),
    ('BAO003', 'el', 'Salmon Bao', 'σολομός teriyaki, αγγούρι, μαρούλι, αβοκάντο, μαγιονέζα λάιμ, σχοινόπρασο, τραγανό κρεμμύδι'),
    ('BAO003', 'en', 'Salmon Bao', 'salmon teriyaki, cucumber, lettuce, avocado, lime mayo, chives, crispy onion'),
    ('BAO003', 'de', 'Lachs Bao', 'Lachs Teriyaki, Gurke, Salat, Avocado, Limetten-Mayo, Schnittlauch, knusprige Zwiebeln'),
    ('BAO003', 'it', 'Bao al Salmone', 'salmone teriyaki, cetriolo, lattuga, avocado, maionese al lime, erba cipollina, cipolla croccante'),
    ('BAO003', 'sv', 'Lax Bao', 'lax teriyaki, gurka, sallad, avokado, lime majonnäs, gräslök, krispig lök'),
    ('BAO004', 'el', 'Mushroom Bao', 'μανιτάρια, αγγούρι, Hoisin mayo, κρεμμυδάκι φρέσκο, σουσάμι'),
    ('BAO004', 'en', 'Mushroom Bao', 'mushroom, cucumber, hoisin mayo, spring onion, sesame'),
    ('BAO004', 'de', 'Pilz Bao', 'Pilze, Gurke, Hoisin-Mayo, Frühlingszwiebel, Sesam'),
    ('BAO004', 'it', 'Bao ai Funghi', 'funghi, cetriolo, maionese hoisin, cipollotto, sesamo'),
    ('BAO004', 'sv', 'Svamp Bao', 'svamp, gurka, hoisin majonnäs, salladslök, sesam'),
    ('BAO005', 'el', 'Duck Bao', 'τραγανή πάπια, αγγούρι, μαρούλι, καρότο, σάλτσα δαμάσκηνου, σχοινόπρασο, σουσάμι'),
    ('BAO005', 'en', 'Duck Bao', 'crispy duck, cucumber, lettuce, carrot, plum sauce, chives, sesame'),
    ('BAO005', 'de', 'Enten Bao', 'knusprige Ente, Gurke, Salat, Karotte, Pflaumensauce, Schnittlauch, Sesam'),
    ('BAO005', 'it', 'Bao all''Anatra', 'anatra croccante, cetriolo, lattuga, carota, salsa di prugne, erba cipollina, sesamo'),
    ('BAO005', 'sv', 'Anka Bao', 'krispig anka, gurka, sallad, morot, plommonsås, gräslök, sesam'),
    ('NO001', 'el', 'Veggie Noodles', 'λάχανο, κρεμμύδι, καρότο, πιπεριές, καλαμπόκι baby, νουντλς mendake, λάδι σουσαμιού, σως τεριγιάκι'),
    ('NO001', 'en', 'Veggie Noodles', 'cabbage, onion, carrot, peppers, baby corn, noodles, sesame oil, teriyaki sauce'),
    ('NO001', 'de', 'Gemüse Nudeln', 'Kohl, Zwiebel, Karotte, Paprika, Babymais, Nudeln, Sesamöl, Teriyaki-Sauce'),
    ('NO001', 'it', 'Noodles Vegetariani', 'cavolo, cipolla, carota, peperoni, mais baby, noodles, olio di sesamo, salsa teriyaki'),
    ('NO001', 'sv', 'Veggie Nudlar', 'kål, lök, morot, paprika, babymajskolvar, nudlar, sesamolja, teriyakisås'),
    ('NO002', 'el', 'Chicken Noodles', 'λάχανο, κρεμμύδι, καρότο, πιπεριές, καλαμπόκι baby, νουντλς αυγού, λάδι σουσαμιού, σως τεριγιάκι'),
    ('NO002', 'en', 'Chicken Noodles', 'cabbage, onion, carrot, peppers, baby corn, egg noodles, sesame oil, teriyaki sauce'),
    ('NO002', 'de', 'Hühnchen Nudeln', 'Kohl, Zwiebel, Karotte, Paprika, Babymais, Eiernudeln, Sesamöl, Teriyaki-Sauce'),
    ('NO002', 'it', 'Noodles al Pollo', 'cavolo, cipolla, carota, peperoni, mais baby, noodles all''uovo, olio di sesamo, salsa teriyaki'),
    ('NO002', 'sv', 'Kyckling Nudlar', 'kål, lök, morot, paprika, babymajskolvar, äggnudlar, sesamolja, teriyakisås'),
    ('NO003', 'el', 'Shrimp Noodles', 'λάχανο, κρεμμύδι, καρότο, πιπεριές, καλαμπόκι baby, νουντλς mendake, λάδι σουσαμιού, σως τεριγιάκι'),
    ('NO003', 'en', 'Shrimp Noodles', 'cabbage, onion, carrot, peppers, baby corn, noodles, sesame oil, teriyaki sauce'),
    ('NO003', 'de', 'Garnelen Nudeln', 'Kohl, Zwiebel, Karotte, Paprika, Babymais, Nudeln, Sesamöl, Teriyaki-Sauce'),
    ('NO003', 'it', 'Noodles ai Gamberi', 'cavolo, cipolla, carota, peperoni, mais baby, noodles, olio di sesamo, salsa teriyaki'),
    ('NO003', 'sv', 'Räk Nudlar', 'kål, lök, morot, paprika, babymajskolvar, nudlar, sesamolja, teriyakisås'),
    ('NO004', 'el', 'Mushroom Yaki Udon', 'μανιτάρια, νουντλς udon, κρεμμυδάκι φρέσκο, σκόρδο, τζίντζερ, σως unagi'),
    ('NO004', 'en', 'Mushroom Yaki Udon', 'mushrooms, udon noodles, spring onion, garlic, ginger, unagi sauce'),
    ('NO004', 'de', 'Pilz Yaki Udon', 'Pilze, Udon-Nudeln, Frühlingszwiebel, Knoblauch, Ingwer, Unagi-Sauce'),
    ('NO004', 'it', 'Udon Yaki ai Funghi', 'funghi, noodles udon, cipollotto, aglio, zenzero, salsa unagi'),
    ('NO004', 'sv', 'Svamp Yaki Udon', 'svamp, udon nudlar, salladslök, vitlök, ingefära, unagi sås'),
    ('NO005', 'el', 'Salmon Yaki Udon', 'γλασαρισμένο φιλέτο σολομού, νουντλς udon, κρεμμυδάκι φρέσκο, καρότο, πιπεριά, σκόρδο, τζίντζερ, σως unagi'),
    ('NO005', 'en', 'Salmon Yaki Udon', 'glazed salmon fillet, udon noodles, spring onion, carrot, pepper, garlic, ginger, unagi sauce'),
    ('NO005', 'de', 'Lachs Yaki Udon', 'glasiertes Lachsfilet, Udon-Nudeln, Frühlingszwiebel, Karotte, Paprika, Knoblauch, Ingwer, Unagi-Sauce'),
    ('NO005', 'it', 'Udon Yaki al Salmone', 'filetto di salmone glassato, noodles udon, cipollotto, carota, peperone, aglio, zenzero, salsa unagi'),
    ('NO005', 'sv', 'Lax Yaki Udon', 'glaserat laxfilé, udon nudlar, salladslök, morot, paprika, vitlök, ingefära, unagi sås'),
    ('NO006', 'el', 'Beef Yaki Udon', 'κιμάς μοσχαρίσιος, νουντλς udon, κρεμμυδάκι φρέσκο, σκόρδο, τζίντζερ, σως unagi'),
    ('NO006', 'en', 'Beef Yaki Udon', 'minced beef, udon noodles, spring onion, garlic, ginger, unagi sauce'),
    ('NO006', 'de', 'Rindfleisch Yaki Udon', 'Rinderhackfleisch, Udon-Nudeln, Frühlingszwiebel, Knoblauch, Ingwer, Unagi-Sauce'),
    ('NO006', 'it', 'Udon Yaki al Manzo', 'carne macinata di manzo, noodles udon, cipollotto, aglio, zenzero, salsa unagi'),
    ('NO006', 'sv', 'Nötkött Yaki Udon', 'malet nötkött, udon nudlar, salladslök, vitlök, ingefära, unagi sås'),
    ('BU001', 'el', 'Beef Melt', 'Μοσχαρίσιο μπιφτέκι black angus, ψωμάκι brioche, μαρούλι iceberg, πιπεριές jalapeno, τυρί τσένταρ'),
    ('BU001', 'en', 'Beef Melt', 'black angus beef burger, brioche bun, iceberg lettuce, jalapeño peppers, cheddar cheese, hoisin mayo'),
    ('BU001', 'de', 'Beef Melt', 'Black-Angus-Rinderburger, Brioche-Bun, Eisbergsalat, Jalapeño-Paprika, Cheddar-Käse, Hoisin-Mayo'),
    ('BU001', 'it', 'Beef Melt', 'hamburger di manzo black angus, panino brioche, lattuga iceberg, peperoni jalapeño, formaggio cheddar, maionese hoisin'),
    ('BU001', 'sv', 'Beef Melt', 'black angus nötköttsburgare, briochebröd, isbergssallad, jalapeñopeppar, cheddarost, hoisin majonnäs'),
    ('BU002', 'el', 'Beef Truffle', 'Μοσχαρίσιο μπιφτέκι black angus, ψωμάκι μπριός, φύλλα μεικτά, παρμεζάνα, σάλτσα μαγιονέζας με τρούφα'),
    ('BU002', 'en', 'Beef Truffle', 'black angus beef burger, brioche bun, mixed leaves, parmesan cheese, truffle mayo'),
    ('BU002', 'de', 'Rinder Trüffel Burger', 'Black-Angus-Rinderburger, Brioche-Bun, gemischte Blätter, Parmesan, Trüffel-Mayo'),
    ('BU002', 'it', 'Beef Tartufo', 'hamburger di manzo black angus, panino brioche, foglie miste, parmigiano, maionese al tartufo'),
    ('BU002', 'sv', 'Nötkött Tryffel', 'black angus nötköttsburgare, briochebröd, blandade blad, parmesanost, tryffel majonnäs'),
    ('BU003', 'el', 'Chicken Katsu Sando', 'τραγανό μπούτι κοτόπουλου, ψωμάκι μπριός, αγγούρι τουρσί, μαρούλι iceberg, σάλτσα μαγιονέζας hoisin'),
    ('BU003', 'en', 'Chicken Katsu Sando', 'crispy chicken thigh, brioche bun, pickled cucumber, iceberg lettuce, hoisin mayo'),
    ('BU003', 'de', 'Chicken Katsu Sando', 'knusperiges Hähnchenschenkel, Brioche-Bun, eingelegte Gurke, Eisbergsalat, Hoisin-Mayo'),
    ('BU003', 'it', 'Chicken Katsu Sando', 'coscia di pollo croccante, panino brioche, cetriolo sottaceto, lattuga iceberg, maionese hoisin'),
    ('BU003', 'sv', 'Chicken Katsu Sando', 'krispigt kycklinglår, briochebröd, inlagd gurka, isbergssallad, hoisin majonnäs'),
    ('BU004', 'el', 'Shrimp & Crab Sando Roll', 'γαρίδες, καβούρι, ψωμάκι μπριός, μαρούλι iceberg, κόκκινο κρεμμύδι τουρσί, τραγανό σκόρδο, σχοινόπρασο, πικάντικη μαγιονέζα'),
    ('BU004', 'en', 'Shrimp & Crab Sando Roll', 'shrimp, crab, brioche bun, iceberg lettuce, pickled red onion, crispy garlic, chives, spicy mayo'),
    ('BU004', 'de', 'Garnelen & Krabbe Sando Roll', 'Garnelen, Krabbe, Brioche-Bun, Eisbergsalat, eingelegte rote Zwiebeln, knuspriger Knoblauch, Schnittlauch, scharfe Mayo'),
    ('BU004', 'it', 'Sando Roll Gamberi & Granchio', 'gamberi, granchio, panino brioche, lattuga iceberg, cipolla rossa sottaceto, aglio croccante, erba cipollina, maionese piccante'),
    ('BU004', 'sv', 'Räk & Krabba Sando Roll', 'räkor, krabba, briochebröd, isbergssallad, inlagd rödlök, krispig vitlök, gräslök, stark majonnäs'),
    ('PO001', 'el', 'Salmon Poke Bowl', 'ρύζι σούσι, μαριναρισμένος σολομός, αβοκάντο, αγγούρι, μάνγκο, τσίλι φασόλια ενταμάμε, φύκι wakame, tobico, σχοινόπρασο, λάιμ, σουσάμι, πικάντικη μαγιονέζα'),
    ('PO001', 'en', 'Salmon Poke Bowl', 'sushi rice, marinated salmon, avocado, cucumber, mango, edamame, wakame, tobico, chives, lime, sesame, spicy mayo'),
    ('PO001', 'de', 'Lachs Poke Bowl', 'Sushi-Reis, marinierter Lachs, Avocado, Gurke, Mango, Edamame, Wakame, Tobiko, Schnittlauch, Limette, Sesam, scharfe Mayo'),
    ('PO001', 'it', 'Poke Bowl al Salmone', 'riso sushi, salmone marinato, avocado, cetriolo, mango, edamame, wakame, tobico, erba cipollina, lime, sesamo, maionese piccante'),
    ('PO001', 'sv', 'Lax Poke Bowl', 'sushiris, marinerad lax, avokado, gurka, mango, edamame, wakame, tobiko, gräslök, lime, sesam, stark majonnäs'),
    ('PO002', 'el', 'Shrimp-Crab Poke Bowl', 'ρύζι σούσι, γαρίδες ποσέ, καβούρι κάνιμι, αβοκάντο, αγγούρι, μάνγκο, φασόλια ενταμάμε, φύκι wakame, tobico, σχοινόπρασο, λάιμ, σουσάμι, πικάντικη μαγιονέζα'),
    ('PO002', 'en', 'Shrimp-Crab Poke Bowl', 'sushi rice, poached shrimp, crab kanimi, avocado, cucumber, mango, edamame, wakame, tobico, chives, lime, sesame, spicy mayo'),
    ('PO002', 'de', 'Garnelen-Krabbe Poke Bowl', 'Sushi-Reis, pochierte Garnelen, Krabben-Kanimi, Avocado, Gurke, Mango, Edamame, Wakame, Tobiko, Schnittlauch, Limette, Sesam, scharfe Mayo'),
    ('PO002', 'it', 'Poke Bowl Gamberi e Granchio', 'riso sushi, gamberi pochés, granchio kanimi, avocado, cetriolo, mango, edamame, wakame, tobico, erba cipollina, lime, sesamo, maionese piccante'),
    ('PO002', 'sv', 'Räk-Krabba Poke Bowl', 'sushiris, pocherade räkor, krabba kanimi, avokado, gurka, mango, edamame, wakame, tobiko, gräslök, lime, sesam, stark majonnäs'),
    ('PO003', 'el', 'Chicken Poke Bowl', 'τραγανό ρύζι, τραγανό κοτόπουλο, αγγούρι, αβοκάντο, καλαμπόκι, κρεμμυδάκια, φύκι, μάνγκο, καρότο, μαγιονέζα, σουσάμι'),
    ('PO003', 'en', 'Chicken Poke Bowl', 'sushi rice, crispy chicken, cucumber, avocado, sweet corn, scallions, seaweed, mango, carrot, mayo, sesame'),
    ('PO003', 'de', 'Hühnchen Poke Bowl', 'Sushi-Reis, knuspriges Hähnchen, Gurke, Avocado, Mais, Frühlingszwiebeln, Meeresalgen, Mango, Karotte, Mayo, Sesam'),
    ('PO003', 'it', 'Poke Bowl al Pollo', 'riso sushi, pollo croccante, cetriolo, avocado, mais dolce, cipollotti, alghe, mango, carota, maionese, sesamo'),
    ('PO003', 'sv', 'Kyckling Poke Bowl', 'sushiris, krispig kyckling, gurka, avokado, majs, salladslök, tång, mango, morot, majonnäs, sesam'),
    ('SA001', 'el', 'Edamame', 'φασόλια ενταμάμε στον ατμό, νιφάδες αλατιού'),
    ('SA001', 'en', 'Edamame', 'steamed edamame, salt flakes'),
    ('SA001', 'de', 'Edamame', 'gedämpfte Edamame, Salzflocken'),
    ('SA001', 'it', 'Edamame', 'edamame al vapore, fiocchi di sale'),
    ('SA001', 'sv', 'Edamame', 'ångad edamame, saltflingor'),
    ('SA002', 'el', 'Kanimi Salad', 'καβούρι kanimi, μαρούλι, αγγούρι, κρεμμύδι φρέσκο, τσίλι, τραγανό ρύζι, τραγανό σκόρδο, ντρέσινγκ σουσάμι'),
    ('SA002', 'en', 'Kanimi Salad', 'crab kanimi, lettuce, cucumber, spring onion, chili, crispy rice, crispy garlic, sesame dressing'),
    ('SA002', 'de', 'Kanimi Salat', 'Krabben-Kanimi, Salat, Gurke, Frühlingszwiebel, Chili, knuspriger Reis, knuspriger Knoblauch, Sesam-Dressing'),
    ('SA002', 'it', 'Insalata Kanimi', 'granchio kanimi, lattuga, cetriolo, cipollotto, peperoncino, riso croccante, aglio croccante, condimento al sesamo'),
    ('SA002', 'sv', 'Kanimi Sallad', 'krabba kanimi, sallad, gurka, salladslök, chili, krispigt ris, krispig vitlök, sesamdressing'),
    ('SA003', 'el', 'Emperor Salad', 'τραγανό κοτόπουλο, μαρούλι iceberg, μαρούλι, αβοκάντο, κάσιου, τραγανό μπέικον, ντρέσινγκ παρμεζάνας'),
    ('SA003', 'en', 'Emperor Salad', 'crispy chicken, iceberg, lettuce, avocado, crispy bacon, cashew nuts, parmesan dressing'),
    ('SA003', 'de', 'Kaiser Salat', 'knuspriges Hähnchen, Eisbergsalat, Avocado, knuspriger Speck, Cashewnüsse, Parmesan-Dressing'),
    ('SA003', 'it', 'Insalata Imperatore', 'pollo croccante, iceberg, lattuga, avocado, pancetta croccante, anacardi, condimento al parmigiano'),
    ('SA003', 'sv', 'Kejsar Sallad', 'krispig kyckling, isbergssallad, avokado, krispig bacon, cashewnötter, parmesandressing'),
    ('SA004', 'el', 'Kaiso Salad', 'φύκι wakame, σουσάμι'),
    ('SA004', 'en', 'Kaiso Salad', 'wakame seaweed, sesame'),
    ('SA004', 'de', 'Kaiso Salat', 'Wakame-Algen, Sesam'),
    ('SA004', 'it', 'Insalata Kaiso', 'alga wakame, sesamo'),
    ('SA004', 'sv', 'Kaiso Sallad', 'wakametång, sesam'),
    ('SA005', 'el', 'Shrimp Noodle Salad', 'γαρίδες, φύλλα μεικτά, νουντλς mendake, φασόλια ενταμάμε, αβοκάντο, παρμεζάνα, πιπεριές, καυτερό ντρέσινγκ λάιμ'),
    ('SA005', 'en', 'Shrimp Noodle Salad', 'shrimp, mixed leaves, mendake noodles, edamame, avocado, parmesan, peppers, spicy lime dressing'),
    ('SA005', 'de', 'Garnelen Nudelsalat', 'Garnelen, gemischte Blätter, Mendake-Nudeln, Edamame, Avocado, Parmesan, Paprika, schärfes Limetten-Dressing'),
    ('SA005', 'it', 'Insalata di Noodles ai Gamberi', 'gamberi, foglie miste, noodles mendake, edamame, avocado, parmigiano, peperoni, condimento piccante al lime'),
    ('SA005', 'sv', 'Räk Nudelsallad', 'räkor, blandade blad, mendake nudlar, edamame, avokado, parmesan, paprika, stark limedressing'),
    ('SA006', 'el', 'Tropical Shrimp Salad', 'γαρίδες, αγγούρι, μάνγκο, αβοκάντο, φύλλα μεικτά, μαγιονέζα passion fruit, σουσάμι'),
    ('SA006', 'en', 'Tropical Shrimp Salad', 'shrimp, cucumber, mango, avocado, mixed leaves, passion fruit mayo, sesame'),
    ('SA006', 'de', 'Tropischer Garnelensalat', 'Garnelen, Gurke, Mango, Avocado, gemischte Blätter, Passionsfrucht-Mayo, Sesam'),
    ('SA006', 'it', 'Insalata Tropicale di Gamberi', 'gamberi, cetriolo, mango, avocado, foglie miste, maionese al frutto della passione, sesamo'),
    ('SA006', 'sv', 'Tropisk Räksallad', 'räkor, gurka, mango, avokado, blandade blad, passionsfrukts majonnäs, sesam'),
    ('DE001', 'el', 'Chocolate Fondant', 'σερβίρεται με παγωτό βανίλια και κρέμα'),
    ('DE001', 'en', 'Chocolate Fondant', 'served with pistachio ice cream and cream'),
    ('DE001', 'de', 'Schokoladenfondant', 'serviert mit Pistazieneis und Sahne'),
    ('DE001', 'it', 'Fondant al Cioccolato', 'servito con gelato al pistacchio e panna'),
    ('DE001', 'sv', 'Chokladfondant', 'serveras med pistaschglass och grädde'),
    ('DE002', 'el', 'Baked Cheesecake', 'σερβίρεται με παγωτό κόκκινων φρούτων και μούρα'),
    ('DE002', 'en', 'Baked Cheesecake', 'served with red fruits ice cream and berries'),
    ('DE002', 'de', 'Gebackener Käsekuchen', 'serviert mit Roten-Früchte-Eis und Beeren'),
    ('DE002', 'it', 'Cheesecake al Forno', 'servita con gelato ai frutti rossi e frutti di bosco'),
    ('DE002', 'sv', 'Bakad Cheesecake', 'serveras med rödfrukts glass och bär'),
    ('DE003', 'el', 'Tiramisu', 'σερβίρεται με παγωτό βανίλια και κέμα'),
    ('DE003', 'en', 'Tiramisu', 'served with vanilla ice cream and cream'),
    ('DE003', 'de', 'Tiramisu', 'serviert mit Vanilleeis und Sahne'),
    ('DE003', 'it', 'Tiramisù', 'servito con gelato alla vaniglia e panna'),
    ('DE003', 'sv', 'Tiramisu', 'serveras med vaniljglass och grädde'),
    ('CO001', 'el', 'Okinawa', 'Japanese Yuzu Aperitif, Shisho, Elderflowe, Carbonated Sake, Strawberry'),
    ('CO001', 'en', 'Okinawa', 'Japanese Yuzu Aperitif, Shiso, Elderflower, Carbonated Sake, Strawberry'),
    ('CO001', 'de', 'Okinawa', 'Japanischer Yuzu-Aperitif, Shiso, Holunderblüte, Kohlensäure-Sake, Erdbeere'),
    ('CO001', 'it', 'Okinawa', 'Aperitivo Yuzu giapponese, Shiso, Sambuco, Sake frizzante, Fragola'),
    ('CO001', 'sv', 'Okinawa', 'Japansk yuzu aperitif, shiso, fläderblomma, kolsyrat sake, jordgubbe'),
    ('CO002', 'el', 'Chihaya', 'Don Julio Tequila Blanco, Cardamom-mustard, Cherries, Nuts, Plum bitters, Clouds'),
    ('CO002', 'en', 'Chihaya', 'Don Julio Tequila Blanco, Cardamom-Mustard, Cherries, Nuts, Plum Bitters, Clouds'),
    ('CO002', 'de', 'Chihaya', 'Don Julio Tequila Blanco, Kardamom-Senf, Kirschen, Nüsse, Pflaumen-Bitters, Clouds'),
    ('CO002', 'it', 'Chihaya', 'Don Julio Tequila Blanco, Cardamomo-senape, Ciliegie, Noci, Bitters di prugna, Clouds'),
    ('CO002', 'sv', 'Chihaya', 'Don Julio Tequila Blanco, Kardemumma-senap, Körsbär, Nötter, Plommonbitters, Clouds'),
    ('CO003', 'el', 'Shirakawa', 'Spiced Ketel One Vodka, Hibiscus, Rhum, Berries, Ginger foam'),
    ('CO003', 'en', 'Shirakawa', 'Spiced Ketel One Vodka, Hibiscus, Rum, Berries, Ginger Foam'),
    ('CO003', 'de', 'Shirakawa', 'Gewürzter Ketel One Vodka, Hibiskus, Rum, Beeren, Ingwerschaum'),
    ('CO003', 'it', 'Shirakawa', 'Vodka Ketel One speziata, Ibisco, Rum, Frutti di bosco, Schiuma di zenzero'),
    ('CO003', 'sv', 'Shirakawa', 'Kryddad Ketel One Vodka, Hibiskus, Rom, Bär, Ingefärsskum'),
    ('CO004', 'el', 'Tsumago', 'Johnie Walker Black Label, Smoke, Pineapple, Jalapeno, Honey, Lemon Juice'),
    ('CO004', 'en', 'Tsumago', 'Johnnie Walker Black Label, Smoke, Pineapple, Jalapeño, Honey, Lemon Juice'),
    ('CO004', 'de', 'Tsumago', 'Johnnie Walker Black Label, Rauch, Ananas, Jalapeño, Honig, Zitronensaft'),
    ('CO004', 'it', 'Tsumago', 'Johnnie Walker Black Label, Affumicato, Ananas, Jalapeño, Miele, Succo di limone'),
    ('CO004', 'sv', 'Tsumago', 'Johnnie Walker Black Label, Rök, Ananas, Jalapeño, Honung, Citronsaft'),
    ('CO005', 'el', 'ギリシャ (Girisha)', 'Mastiha, Oolong tea, Ponzu citrus, Pickled peach, Aromatic bitters'),
    ('CO005', 'en', 'ギリシャ (Girisha)', 'Mastiha, Oolong Tea, Ponzu Citrus, Pickled Peach, Aromatic Bitters'),
    ('CO005', 'de', 'ギリシャ (Girisha)', 'Mastix, Oolong-Tee, Ponzu-Zitrus, eingelegte Pfirsiche, aromatische Bitters'),
    ('CO005', 'it', 'ギリシャ (Girisha)', 'Mastiha, Tè oolong, Agrumi ponzu, Pesca sottaceto, Bitters aromatici'),
    ('CO005', 'sv', 'ギリシャ (Girisha)', 'Mastika, Oolongte, Ponzucitrus, Inlagd persika, Aromatisk bitter'),
    ('CO006', 'el', 'Japanese Opioum', 'Vodka, Le Citron, Jasmine Syrup, Lime Juice, Green Apple Liqueur'),
    ('CO006', 'en', 'Japanese Opioum', 'Vodka, Citron Liqueur, Jasmine Syrup, Lime Juice, Green Apple Liqueur'),
    ('CO006', 'de', 'Japanese Opioum', 'Vodka, Zitronenlikör, Jasmin-Sirup, Limettensaft, Grüner Apfellikör'),
    ('CO006', 'it', 'Japanese Opioum', 'Vodka, Liquore al limone, Sciroppo di gelsomino, Succo di lime, Liquore di mela verde'),
    ('CO006', 'sv', 'Japanese Opioum', 'Vodka, citronlikör, jasminsirap, limejuice, grön äpplelikör'),
    ('CO007', 'el', 'Yugen', 'Tanqueray 10 Gin, Mandarin, Botanicals, Lemon Juice, Yuzu coconut foam'),
    ('CO007', 'en', 'Yugen', 'Tanqueray No. 10 Gin, Mandarin, Botanicals, Lemon Juice, Yuzu Coconut Foam'),
    ('CO007', 'de', 'Yugen', 'Tanqueray No. 10 Gin, Mandarine, Botanicals, Zitronensaft, Yuzu-Kokos-Schaum'),
    ('CO007', 'it', 'Yugen', 'Tanqueray No. 10 Gin, Mandarino, Botanicals, Succo di limone, Schiuma di cocco yuzu'),
    ('CO007', 'sv', 'Yugen', 'Tanqueray No. 10 Gin, Mandarin, Botanicals, Citronsaft, Yuzu-kokosskum'),
    ('CO008', 'el', 'Kintsugi Sour', 'Johnie Walker Black Ruby, Vanilla, Banana, Lemon Peel, Lime, Clouds'),
    ('CO008', 'en', 'Kintsugi Sour', 'Johnnie Walker Black Ruby, Vanilla, Banana, Lemon Peel, Lime, Clouds'),
    ('CO008', 'de', 'Kintsugi Sour', 'Johnnie Walker Black Ruby, Vanille, Banane, Zitronenschale, Limette, Clouds'),
    ('CO008', 'it', 'Kintsugi Sour', 'Johnnie Walker Black Ruby, Vaniglia, Banana, Buccia di limone, Lime, Clouds'),
    ('CO008', 'sv', 'Kintsugi Sour', 'Johnnie Walker Black Ruby, Vanilj, Banan, Citronskal, Lime, Clouds'),
    ('CO009', 'el', 'Tsukimi Glow', 'Tanqueray Gin, Passion fruit, Rhubarb Liqueur, Pink Grapefruit Soda'),
    ('CO009', 'en', 'Tsukimi Glow', 'Tanqueray Gin, Passion Fruit, Rhubarb Liqueur, Pink Grapefruit Soda'),
    ('CO009', 'de', 'Tsukimi Glow', 'Tanqueray Gin, Passionsfrucht, Rhabarberlikör, Rosa Grapefruit-Soda'),
    ('CO009', 'it', 'Tsukimi Glow', 'Tanqueray Gin, Frutto della passione, Liquore al rabarbaro, Soda al pompelmo rosa'),
    ('CO009', 'sv', 'Tsukimi Glow', 'Tanqueray Gin, Passionsfrukt, Rabarberslikör, Rosa grapefruktläsk'),
    ('CO010', 'el', 'Amaterasu Light', 'Captain Morgan Rum, Zacapa Rum, Melon, Lemon Juice, Mint Leaves'),
    ('CO010', 'en', 'Amaterasu Light', 'Captain Morgan Rum, Zacapa Rum, Melon, Lemon Juice, Mint Leaves'),
    ('CO010', 'de', 'Amaterasu Light', 'Captain Morgan Rum, Zacapa Rum, Melone, Zitronensaft, Minzblätter'),
    ('CO010', 'it', 'Amaterasu Light', 'Rum Captain Morgan, Rum Zacapa, Melone, Succo di limone, Foglie di menta'),
    ('CO010', 'sv', 'Amaterasu Light', 'Captain Morgan Rum, Zacapa Rum, Melon, Citronsaft, Myntablad'),
    ('CC001', 'el', 'Margarita', 'Classic Margarita cocktail'),
    ('CC001', 'en', 'Margarita', 'Tequila, triple sec, lime juice, salt rim'),
    ('CC001', 'de', 'Margarita', 'Tequila, Triple Sec, Limettensaft, Salzrand'),
    ('CC001', 'it', 'Margarita', 'Tequila, triple sec, succo di lime, bordo di sale'),
    ('CC001', 'sv', 'Margarita', 'Tequila, triple sec, limejuice, saltrand'),
    ('CC002', 'el', 'Daiquiri', 'Classic Daiquiri cocktail'),
    ('CC002', 'en', 'Daiquiri', 'Rum, lime juice, sugar'),
    ('CC002', 'de', 'Daiquiri', 'Rum, Limettensaft, Zucker'),
    ('CC002', 'it', 'Daiquiri', 'Rum, succo di lime, zucchero'),
    ('CC002', 'sv', 'Daiquiri', 'Rom, limejuice, socker'),
    ('CC003', 'el', 'Porn Star Martini', 'Classic Porn Star Martini cocktail'),
    ('CC003', 'en', 'Porn Star Martini', 'Vanilla vodka, passion fruit liqueur, passion fruit, prosecco'),
    ('CC003', 'de', 'Porn Star Martini', 'Vanille-Vodka, Passionsfruchtlikör, Passionsfrucht, Prosecco'),
    ('CC003', 'it', 'Porn Star Martini', 'Vodka alla vaniglia, liquore al frutto della passione, frutto della passione, prosecco'),
    ('CC003', 'sv', 'Porn Star Martini', 'Vaniljvodka, passionsfruktslikör, passionsfrukt, prosecco'),
    ('CC004', 'el', 'Gin Basil Smash', 'Classic Gin Basil Smash cocktail'),
    ('CC004', 'en', 'Gin Basil Smash', 'Gin, fresh basil, lemon juice, sugar syrup'),
    ('CC004', 'de', 'Gin Basilikum Smash', 'Gin, frisches Basilikum, Zitronensaft, Zuckersirup'),
    ('CC004', 'it', 'Gin Basil Smash', 'Gin, basilico fresco, succo di limone, sciroppo di zucchero'),
    ('CC004', 'sv', 'Gin Basilika Smash', 'Gin, färsk basilika, citronsaft, sockerlag'),
    ('CC005', 'el', 'Paloma', 'Classic Paloma cocktail'),
    ('CC005', 'en', 'Paloma', 'Tequila, grapefruit soda, lime juice, salt'),
    ('CC005', 'de', 'Paloma', 'Tequila, Grapefruitsoda, Limettensaft, Salz'),
    ('CC005', 'it', 'Paloma', 'Tequila, soda al pompelmo, succo di lime, sale'),
    ('CC005', 'sv', 'Paloma', 'Tequila, grapefruktsläsk, limejuice, salt'),
    ('CC006', 'el', 'Mai Tai', 'Classic Mai Tai cocktail'),
    ('CC006', 'en', 'Mai Tai', 'Rum, orange curaçao, lime juice, orgeat syrup'),
    ('CC006', 'de', 'Mai Tai', 'Rum, Orangen-Curaçao, Limettensaft, Orgeat-Sirup'),
    ('CC006', 'it', 'Mai Tai', 'Rum, curaçao all''arancia, succo di lime, sciroppo di orgeat'),
    ('CC006', 'sv', 'Mai Tai', 'Rom, orange curaçao, limejuice, orgeatsirap'),
    ('CC007', 'el', 'Zombie', 'Classic Zombie cocktail'),
    ('CC007', 'en', 'Zombie', 'Three types of rum, fruit juices, grenadine'),
    ('CC007', 'de', 'Zombie', 'Drei Rumsorten, Fruchtsäfte, Grenadine'),
    ('CC007', 'it', 'Zombie', 'Tre tipi di rum, succhi di frutta, granatina'),
    ('CC007', 'sv', 'Zombie', 'Tre typer av rom, fruktjuicer, grenadinsirap'),
    ('CC008', 'el', 'Espresso Martini', 'Classic Espresso Martini cocktail'),
    ('CC008', 'en', 'Espresso Martini', 'Vodka, coffee liqueur, espresso, sugar syrup'),
    ('CC008', 'de', 'Espresso Martini', 'Vodka, Kaffeelikör, Espresso, Zuckersirup'),
    ('CC008', 'it', 'Espresso Martini', 'Vodka, liquore al caffè, espresso, sciroppo di zucchero'),
    ('CC008', 'sv', 'Espresso Martini', 'Vodka, kaffelikör, espresso, sockerlag'),
    ('CC009', 'el', 'Long Drinks', 'Classic Long Drinks'),
    ('CC009', 'en', 'Long Drinks', 'Classic long drinks selection'),
    ('CC009', 'de', 'Long Drinks', 'Klassische Long-Drink-Auswahl'),
    ('CC009', 'it', 'Long Drinks', 'Selezione di long drink classici'),
    ('CC009', 'sv', 'Long Drinks', 'Klassiskt urval av long drinks'),
    ('MO001', 'el', 'Takaragawa', 'Tanqueray 0%, cherries, pickled peach'),
    ('MO001', 'en', 'Takaragawa', 'Tanqueray 0%, cherries, pickled peach'),
    ('MO001', 'de', 'Takaragawa', 'Tanqueray 0%, Kirschen, eingelegte Pfirsiche'),
    ('MO001', 'it', 'Takaragawa', 'Tanqueray 0%, ciliegie, pesca sottaceto'),
    ('MO001', 'sv', 'Takaragawa', 'Tanqueray 0%, körsbär, inlagd persika'),
    ('MO002', 'el', 'Bonsai Breeze', 'Tanqueray 0%, Passion fruit, Tangerine, Black tea, Lemon juice'),
    ('MO002', 'en', 'Bonsai Breeze', 'Tanqueray 0%, passion fruit, tangerine, black tea, lemon juice'),
    ('MO002', 'de', 'Bonsai Breeze', 'Tanqueray 0%, Passionsfrucht, Mandarine, Schwarztee, Zitronensaft'),
    ('MO002', 'it', 'Bonsai Breeze', 'Tanqueray 0%, frutto della passione, mandarino, tè nero, succo di limone'),
    ('MO002', 'sv', 'Bonsai Breeze', 'Tanqueray 0%, passionsfrukt, mandarin, svart te, citronsaft'),
    ('DR001', 'el', 'Still Water 1lt', 'Still water 1 litre'),
    ('DR001', 'en', 'Still Water 1lt', 'Still water 1 litre'),
    ('DR001', 'de', 'Stilles Wasser 1L', 'Stilles Wasser 1 Liter'),
    ('DR001', 'it', 'Acqua Naturale 1lt', 'Acqua naturale 1 litro'),
    ('DR001', 'sv', 'Stilla Vatten 1L', 'Stilla vatten 1 liter'),
    ('DR002', 'el', 'S.Pellegrino 750ml', 'Sparkling water 750ml'),
    ('DR002', 'en', 'S.Pellegrino 750ml', 'Sparkling mineral water 750ml'),
    ('DR002', 'de', 'S.Pellegrino 750ml', 'Sprudelwasser 750ml'),
    ('DR002', 'it', 'S.Pellegrino 750ml', 'Acqua minerale frizzante 750ml'),
    ('DR002', 'sv', 'S.Pellegrino 750ml', 'Kolsyrat mineralvatten 750ml'),
    ('DR003', 'el', 'Three Cents Pink Grapefruit Soda', 'Pink grapefruit soda 200ml'),
    ('DR003', 'en', 'Three Cents Pink Grapefruit Soda', 'Pink grapefruit soda 200ml'),
    ('DR003', 'de', 'Three Cents Rosa Grapefruit Soda', 'Rosa Grapefruitsoda 200ml'),
    ('DR003', 'it', 'Three Cents Soda al Pompelmo Rosa', 'Soda al pompelmo rosa 200ml'),
    ('DR003', 'sv', 'Three Cents Rosa Grapefruktläsk', 'Rosa grapefruktläsk 200ml'),
    ('DR004', 'el', 'Espresso', 'Espresso coffee'),
    ('DR004', 'en', 'Espresso', 'Espresso coffee'),
    ('DR004', 'de', 'Espresso', 'Espresso-Kaffee'),
    ('DR004', 'it', 'Espresso', 'Caffè espresso'),
    ('DR004', 'sv', 'Espresso', 'Espressokaffe'),
    ('DR005', 'el', 'Tea', 'Tea'),
    ('DR005', 'en', 'Tea', 'Tea'),
    ('DR005', 'de', 'Tee', 'Tee'),
    ('DR005', 'it', 'Tè', 'Tè'),
    ('DR005', 'sv', 'Te', 'Te'),
    ('CI001', 'el', 'Milokleftis Greek Apple Cider', 'Greek apple cider, 330ml, alc 4.5%'),
    ('CI001', 'en', 'Milokleftis Greek Apple Cider', 'Greek apple cider, 330ml, 4.5% alc.'),
    ('CI001', 'de', 'Milokleftis Griechischer Apfelcider', 'Griechischer Apfelcider, 330ml, 4,5% Alk.'),
    ('CI001', 'it', 'Milokleftis Sidro di Mele Greco', 'Sidro di mele greco, 330ml, alc. 4,5%'),
    ('CI001', 'sv', 'Milokleftis Grekisk Äppelcider', 'Grekisk äppelcider, 330ml, 4,5% alc.'),
    ('CI002', 'el', 'Strongbow Red Berries', 'Cider with red berries, 330ml, alc 4.5%'),
    ('CI002', 'en', 'Strongbow Red Berries Cider', 'Cider with red berries, 330ml, 4.5% alc.'),
    ('CI002', 'de', 'Strongbow Rote Beeren Cider', 'Cider mit roten Beeren, 330ml, 4,5% Alk.'),
    ('CI002', 'it', 'Strongbow Sidro Frutti Rossi', 'Sidro ai frutti rossi, 330ml, alc. 4,5%'),
    ('CI002', 'sv', 'Strongbow Röda Bär Cider', 'Cider med röda bär, 330ml, 4,5% alc.'),
    ('BE001', 'el', 'Heineken Draft', 'Lager, 400ml, alc 5%'),
    ('BE001', 'en', 'Heineken Draft', 'Lager, 400ml, 5% alc.'),
    ('BE001', 'de', 'Heineken Fassbier', 'Lager, 400ml, 5% Alk.'),
    ('BE001', 'it', 'Heineken alla Spina', 'Lager, 400ml, alc. 5%'),
    ('BE001', 'sv', 'Heineken Fatöl', 'Lager, 400ml, 5% alc.'),
    ('BE002', 'el', 'Alfa Lager', 'Lager, 330ml, alc 5%'),
    ('BE002', 'en', 'Alfa Lager', 'Greek lager, 330ml, 5% alc.'),
    ('BE002', 'de', 'Alfa Lager', 'Griechisches Lagerbier, 330ml, 5% Alk.'),
    ('BE002', 'it', 'Alfa Lager', 'Lager greco, 330ml, alc. 5%'),
    ('BE002', 'sv', 'Alfa Lager', 'Grekisk lager, 330ml, 5% alc.'),
    ('BE003', 'el', 'Amstel Radler', 'Lemon Radler, 330ml, alc 4.2%'),
    ('BE003', 'en', 'Amstel Radler', 'Lemon radler, 330ml, 4.2% alc.'),
    ('BE003', 'de', 'Amstel Radler', 'Zitronen-Radler, 330ml, 4,2% Alk.'),
    ('BE003', 'it', 'Amstel Radler', 'Radler al limone, 330ml, alc. 4,2%'),
    ('BE003', 'sv', 'Amstel Radler', 'Citron radler, 330ml, 4,2% alc.'),
    ('BE004', 'el', 'Mamos Pilsner', 'Pilsner, 330ml, alc 5%'),
    ('BE004', 'en', 'Mamos Pilsner', 'Pilsner, 330ml, 5% alc.'),
    ('BE004', 'de', 'Mamos Pilsner', 'Pilsner, 330ml, 5% Alk.'),
    ('BE004', 'it', 'Mamos Pilsner', 'Pilsner, 330ml, alc. 5%'),
    ('BE004', 'sv', 'Mamos Pilsner', 'Pilsner, 330ml, 5% alc.'),
    ('BE005', 'el', 'Erdinger Weiss', 'Weiss beer, 330ml, alc 5.3%'),
    ('BE005', 'en', 'Erdinger Weiss', 'Wheat beer, 330ml, 5.3% alc.'),
    ('BE005', 'de', 'Erdinger Weißbier', 'Weißbier, 330ml, 5,3% Alk.'),
    ('BE005', 'it', 'Erdinger Weiss', 'Birra di frumento, 330ml, alc. 5,3%'),
    ('BE005', 'sv', 'Erdinger Weiss', 'Veteöl, 330ml, 5,3% alc.'),
    ('BE006', 'el', 'Sol Exotic Lager', 'Exotic Lager, 330ml, alc 4.2%'),
    ('BE006', 'en', 'Sol Exotic Lager', 'Exotic lager, 330ml, 4.2% alc.'),
    ('BE006', 'de', 'Sol Exotic Lager', 'Exotisches Lager, 330ml, 4,2% Alk.'),
    ('BE006', 'it', 'Sol Exotic Lager', 'Lager esotico, 330ml, alc. 4,2%'),
    ('BE006', 'sv', 'Sol Exotic Lager', 'Exotisk lager, 330ml, 4,2% alc.'),
    ('BE007', 'el', 'Asahi Dry Japanese Beer', 'Dry Japanese beer, 330ml'),
    ('BE007', 'en', 'Asahi Dry Japanese Beer', 'Dry Japanese beer, 330ml'),
    ('BE007', 'de', 'Asahi Dry Japanisches Bier', 'Trockenes japanisches Bier, 330ml'),
    ('BE007', 'it', 'Asahi Dry Birra Giapponese', 'Birra giapponese dry, 330ml'),
    ('BE007', 'sv', 'Asahi Dry Japanskt Öl', 'Torrt japanskt öl, 330ml'),
    ('WH001', 'el', 'Johnnie Walker Red Label', 'Blended Scotch Whisky'),
    ('WH001', 'en', 'Johnnie Walker Red Label', 'Blended Scotch Whisky'),
    ('WH001', 'de', 'Johnnie Walker Red Label', 'Blended Scotch Whisky'),
    ('WH001', 'it', 'Johnnie Walker Red Label', 'Scotch Whisky Blended'),
    ('WH001', 'sv', 'Johnnie Walker Red Label', 'Blandad Scotch Whisky'),
    ('WH002', 'el', 'Johnnie Walker Black Label', 'Blended Scotch Whisky 12 years'),
    ('WH002', 'en', 'Johnnie Walker Black Label', 'Blended Scotch Whisky, 12 years'),
    ('WH002', 'de', 'Johnnie Walker Black Label', 'Blended Scotch Whisky, 12 Jahre'),
    ('WH002', 'it', 'Johnnie Walker Black Label', 'Scotch Whisky Blended, 12 anni'),
    ('WH002', 'sv', 'Johnnie Walker Black Label', 'Blandad Scotch Whisky, 12 år'),
    ('WH003', 'el', 'Dewar''s', 'Blended Scotch Whisky'),
    ('WH003', 'en', 'Dewar''s', 'Blended Scotch Whisky'),
    ('WH003', 'de', 'Dewar''s', 'Blended Scotch Whisky'),
    ('WH003', 'it', 'Dewar''s', 'Scotch Whisky Blended'),
    ('WH003', 'sv', 'Dewar''s', 'Blandad Scotch Whisky'),
    ('WH004', 'el', 'Metaxa 5 Stars', 'Greek spirit'),
    ('WH004', 'en', 'Metaxa 5 Stars', 'Greek aged spirit'),
    ('WH004', 'de', 'Metaxa 5 Sterne', 'Griechischer gereifter Weinbrand'),
    ('WH004', 'it', 'Metaxa 5 Stelle', 'Distillato greco invecchiato'),
    ('WH004', 'sv', 'Metaxa 5 Stjärnor', 'Grekisk lagrad sprit'),
    ('WW001', 'el', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · glass: 7.00'),
    ('WW001', 'en', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · glass: €7'),
    ('WW001', 'de', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · Glas: 7€'),
    ('WW001', 'it', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · calice: 7€'),
    ('WW001', 'sv', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · glas: 7€'),
    ('WW002', 'el', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Muscat · glass: 7.00'),
    ('WW002', 'en', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Muscat · glass: €7'),
    ('WW002', 'de', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Muskat · Glas: 7€'),
    ('WW002', 'it', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Moscato · calice: 7€'),
    ('WW002', 'sv', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Muscat · glas: 7€'),
    ('WW003', 'el', 'Propodes | Domaine Zafeirakis', 'Chardonnay'),
    ('WW003', 'en', 'Propodes | Domaine Zafeirakis', 'Chardonnay'),
    ('WW003', 'de', 'Propodes | Domaine Zafeirakis', 'Chardonnay'),
    ('WW003', 'it', 'Propodes | Domaine Zafeirakis', 'Chardonnay'),
    ('WW003', 'sv', 'Propodes | Domaine Zafeirakis', 'Chardonnay'),
    ('WW004', 'el', 'Megathiri | Tatakis Wines', 'Athiri'),
    ('WW004', 'en', 'Megathiri | Tatakis Wines', 'Athiri'),
    ('WW004', 'de', 'Megathiri | Tatakis Wines', 'Athiri'),
    ('WW004', 'it', 'Megathiri | Tatakis Wines', 'Athiri'),
    ('WW004', 'sv', 'Megathiri | Tatakis Wines', 'Athiri'),
    ('WW005', 'el', 'Theros Wine Collectiva', 'Thrapsathiri'),
    ('WW005', 'en', 'Theros Wine Collectiva', 'Thrapsathiri'),
    ('WW005', 'de', 'Theros Wine Collectiva', 'Thrapsathiri'),
    ('WW005', 'it', 'Theros Wine Collectiva', 'Thrapsathiri'),
    ('WW005', 'sv', 'Theros Wine Collectiva', 'Thrapsathiri'),
    ('WW006', 'el', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko'),
    ('WW006', 'en', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko'),
    ('WW006', 'de', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko'),
    ('WW006', 'it', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko'),
    ('WW006', 'sv', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko'),
    ('WW007', 'el', 'Akrathos Newlands Winery', 'Assyrtiko'),
    ('WW007', 'en', 'Akrathos Newlands Winery', 'Assyrtiko'),
    ('WW007', 'de', 'Akrathos Newlands Winery', 'Assyrtiko'),
    ('WW007', 'it', 'Akrathos Newlands Winery', 'Assyrtiko'),
    ('WW007', 'sv', 'Akrathos Newlands Winery', 'Assyrtiko'),
    ('WW008', 'el', 'Domaine Costa Lazaridi', 'Semillon'),
    ('WW008', 'en', 'Domaine Costa Lazaridi', 'Semillon'),
    ('WW008', 'de', 'Domaine Costa Lazaridi', 'Semillon'),
    ('WW008', 'it', 'Domaine Costa Lazaridi', 'Semillon'),
    ('WW008', 'sv', 'Domaine Costa Lazaridi', 'Semillon'),
    ('WW009', 'el', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc'),
    ('WW009', 'en', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc'),
    ('WW009', 'de', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc'),
    ('WW009', 'it', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc'),
    ('WW009', 'sv', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc'),
    ('WW010', 'el', 'Weingut Thorle', 'Riesling off dry'),
    ('WW010', 'en', 'Weingut Thorle', 'Riesling off dry'),
    ('WW010', 'de', 'Weingut Thorle', 'Riesling halbtrocken'),
    ('WW010', 'it', 'Weingut Thorle', 'Riesling abboccato'),
    ('WW010', 'sv', 'Weingut Thorle', 'Riesling halvtorrt'),
    ('WW011', 'el', 'Bourgogne / Domaine David Moret', 'Chardonnay'),
    ('WW011', 'en', 'Bourgogne / Domaine David Moret', 'Chardonnay'),
    ('WW011', 'de', 'Bourgogne / Domaine David Moret', 'Chardonnay'),
    ('WW011', 'it', 'Bourgogne / Domaine David Moret', 'Chardonnay'),
    ('WW011', 'sv', 'Bourgogne / Domaine David Moret', 'Chardonnay'),
    ('RO001', 'el', '4-6H | Gaia Wines', 'Agiorgitiko · glass: 7.00'),
    ('RO001', 'en', '4-6H | Gaia Wines', 'Agiorgitiko rosé · glass: €7'),
    ('RO001', 'de', '4-6H | Gaia Wines', 'Agiorgitiko Rosé · Glas: 7€'),
    ('RO001', 'it', '4-6H | Gaia Wines', 'Agiorgitiko rosato · calice: 7€'),
    ('RO001', 'sv', '4-6H | Gaia Wines', 'Agiorgitiko rosé · glas: 7€'),
    ('RO002', 'el', 'Joker Semi Dry | Liappis Boutique Winery', 'Muscat, Syrah · glass: 7.00'),
    ('RO002', 'en', 'Joker Semi Dry | Liappis Boutique Winery', 'Muscat, Syrah rosé · glass: €7'),
    ('RO002', 'de', 'Joker Halbtrocken | Liappis Boutique Winery', 'Muskat, Syrah Rosé · Glas: 7€'),
    ('RO002', 'it', 'Joker Semi Dry | Liappis Boutique Winery', 'Moscato, Syrah rosato · calice: 7€'),
    ('RO002', 'sv', 'Joker Halvtorrt | Liappis Boutique Winery', 'Muscat, Syrah rosé · glas: 7€'),
    ('RO003', 'el', 'Maissa | Tatakis Wines', 'Syrah, Merlot'),
    ('RO003', 'en', 'Maissa | Tatakis Wines', 'Syrah, Merlot rosé'),
    ('RO003', 'de', 'Maissa | Tatakis Wines', 'Syrah, Merlot Rosé'),
    ('RO003', 'it', 'Maissa | Tatakis Wines', 'Syrah, Merlot rosato'),
    ('RO003', 'sv', 'Maissa | Tatakis Wines', 'Syrah, Merlot rosé'),
    ('RO004', 'el', 'Techni Alipias | Wine Art Estate', 'Syrah'),
    ('RO004', 'en', 'Techni Alipias | Wine Art Estate', 'Syrah rosé'),
    ('RO004', 'de', 'Techni Alipias | Wine Art Estate', 'Syrah Rosé'),
    ('RO004', 'it', 'Techni Alipias | Wine Art Estate', 'Syrah rosato'),
    ('RO004', 'sv', 'Techni Alipias | Wine Art Estate', 'Syrah rosé'),
    ('RO005', 'el', 'Domaine Costa Lazaridi Rose', 'Merlot, Agiorgitiko, Syrah'),
    ('RO005', 'en', 'Domaine Costa Lazaridi Rosé', 'Merlot, Agiorgitiko, Syrah rosé'),
    ('RO005', 'de', 'Domaine Costa Lazaridi Rosé', 'Merlot, Agiorgitiko, Syrah Rosé'),
    ('RO005', 'it', 'Domaine Costa Lazaridi Rosato', 'Merlot, Agiorgitiko, Syrah rosato'),
    ('RO005', 'sv', 'Domaine Costa Lazaridi Rosé', 'Merlot, Agiorgitiko, Syrah rosé'),
    ('RO006', 'el', 'Alpha Estate', 'Xinomavro'),
    ('RO006', 'en', 'Alpha Estate', 'Xinomavro rosé'),
    ('RO006', 'de', 'Alpha Estate', 'Xinomavro Rosé'),
    ('RO006', 'it', 'Alpha Estate', 'Xinomavro rosato'),
    ('RO006', 'sv', 'Alpha Estate', 'Xinomavro rosé'),
    ('RO007', 'el', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah'),
    ('RO007', 'en', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah rosé'),
    ('RO007', 'de', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah Rosé'),
    ('RO007', 'it', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah rosato'),
    ('RO007', 'sv', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah rosé'),
    ('RO008', 'el', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourverde, Rolle'),
    ('RO008', 'en', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourvèdre, Rolle rosé'),
    ('RO008', 'de', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourvèdre, Rolle Rosé'),
    ('RO008', 'it', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourvèdre, Rolle rosato'),
    ('RO008', 'sv', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourvèdre, Rolle rosé'),
    ('RE001', 'el', 'Kompsos | Karavitakis Winery', 'Liatiko · glass: 7.00'),
    ('RE001', 'en', 'Kompsos | Karavitakis Winery', 'Liatiko red · glass: €7'),
    ('RE001', 'de', 'Kompsos | Karavitakis Winery', 'Liatiko Rotwein · Glas: 7€'),
    ('RE001', 'it', 'Kompsos | Karavitakis Winery', 'Liatiko rosso · calice: 7€'),
    ('RE001', 'sv', 'Kompsos | Karavitakis Winery', 'Liatiko rödvin · glas: 7€'),
    ('RE002', 'el', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot'),
    ('RE002', 'en', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot red'),
    ('RE002', 'de', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot Rotwein'),
    ('RE002', 'it', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot rosso'),
    ('RE002', 'sv', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot rödvin'),
    ('RE003', 'el', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot'),
    ('RE003', 'en', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot'),
    ('RE003', 'de', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot'),
    ('RE003', 'it', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot'),
    ('RE003', 'sv', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot'),
    ('SP001', 'el', 'Martini Prosecco D.O.C', 'Prosecco · glass: 8.00'),
    ('SP001', 'en', 'Martini Prosecco D.O.C', 'Prosecco · glass: €8'),
    ('SP001', 'de', 'Martini Prosecco D.O.C', 'Prosecco · Glas: 8€'),
    ('SP001', 'it', 'Martini Prosecco D.O.C', 'Prosecco · calice: 8€'),
    ('SP001', 'sv', 'Martini Prosecco D.O.C', 'Prosecco · glas: 8€'),
    ('SP002', 'el', 'Martini Asti Semi Sweet', 'Semi sweet sparkling · glass: 8.00'),
    ('SP002', 'en', 'Martini Asti Semi Sweet', 'Semi-sweet sparkling wine · glass: €8'),
    ('SP002', 'de', 'Martini Asti Halbsüß', 'Halbsüßer Schaumwein · Glas: 8€'),
    ('SP002', 'it', 'Martini Asti Semidolce', 'Spumante semidolce · calice: 8€'),
    ('SP002', 'sv', 'Martini Asti Halvsött', 'Halvt sött mousserande vin · glas: 8€'),
    ('SP003', 'el', 'Moet & Chandon Ice Imperial', 'Champagne served over ice'),
    ('SP003', 'en', 'Moët & Chandon Ice Imperial', 'Champagne served over ice'),
    ('SP003', 'de', 'Moët & Chandon Ice Imperial', 'Champagner auf Eis serviert'),
    ('SP003', 'it', 'Moët & Chandon Ice Imperial', 'Champagne servito sul ghiaccio'),
    ('SP003', 'sv', 'Moët & Chandon Ice Imperial', 'Champagne serverad på is'),
    ('SP004', 'el', 'Moet & Chandon Rose Imperial Brut', 'Rose Champagne Brut'),
    ('SP004', 'en', 'Moët & Chandon Rosé Imperial Brut', 'Rosé Champagne Brut'),
    ('SP004', 'de', 'Moët & Chandon Rosé Imperial Brut', 'Rosé-Champagner Brut'),
    ('SP004', 'it', 'Moët & Chandon Rosé Imperial Brut', 'Champagne rosé Brut'),
    ('SP004', 'sv', 'Moët & Chandon Rosé Imperial Brut', 'Rosé Champagne Brut'),
    ('SP005', 'el', 'Louis Roederer Brut Collection', 'Champagne Brut Collection'),
    ('SP005', 'en', 'Louis Roederer Brut Collection', 'Champagne Brut Collection'),
    ('SP005', 'de', 'Louis Roederer Brut Collection', 'Champagner Brut Collection'),
    ('SP005', 'it', 'Louis Roederer Brut Collection', 'Champagne Brut Collection'),
    ('SP005', 'sv', 'Louis Roederer Brut Collection', 'Champagne Brut Collection'),
    ('SH001', 'el', 'Shisha', 'Διαθέσιμες γεύσεις: Blue ice, Forest pulp (strawberry, berry), Alter ego (berry, mango, mint), Knock out (passion fruit, mango), Watermellon, Peach, Lemon mint, Two apples (green, red)'),
    ('SH001', 'en', 'Shisha', 'Available flavors: Blue ice, Forest pulp (strawberry, berry), Alter ego (berry, mango, mint), Knock out (passion fruit, mango), Watermelon, Peach, Lemon mint, Two apples (green, red)'),
    ('SH001', 'de', 'Shisha', 'Verfügbare Sorten: Blue ice, Forest pulp (Erdbeere, Beere), Alter ego (Beere, Mango, Minze), Knock out (Passionsfrucht, Mango), Wassermelone, Pfirsich, Zitronenminze, Zwei Äpfel (grün, rot)'),
    ('SH001', 'it', 'Shisha', 'Sapori disponibili: Blue ice, Forest pulp (fragola, frutti di bosco), Alter ego (frutti di bosco, mango, menta), Knock out (frutto della passione, mango), Anguria, Pesca, Menta limone, Due mele (verde, rossa)'),
    ('SH001', 'sv', 'Shisha', 'Tillgängliga smaker: Blue ice, Forest pulp (jordgubbe, bär), Alter ego (bär, mango, mynta), Knock out (passionsfrukt, mango), Vattenmelon, Persika, Citronmynta, Två äpplen (grönt, rött)')
) as v(external_id, language_code, name, description)
join menu_items mi on mi.external_id = v.external_id
on conflict (menu_item_id, language_code) do update
set
    name = excluded.name,
    description = excluded.description,
    updated_at = now();

commit;
