-- Generated by backend/scripts/generate_menu_seed_sql.py --language tr.
-- Adds 'tr' to the language constraints and inserts its translation
-- rows. Idempotent and non-destructive: existing rows are left untouched
-- (ON CONFLICT DO NOTHING), so admin-edited data survives.

begin;

alter table menu_category_translations
    drop constraint if exists ck_menu_category_translations_language;

alter table menu_category_translations
    add constraint ck_menu_category_translations_language
    check (language_code in ('el', 'en', 'de', 'it', 'sv', 'fr', 'ru', 'he', 'tr'));

alter table menu_item_translations
    drop constraint if exists ck_menu_item_translations_language;

alter table menu_item_translations
    add constraint ck_menu_item_translations_language
    check (language_code in ('el', 'en', 'de', 'it', 'sv', 'fr', 'ru', 'he', 'tr'));

insert into menu_category_translations (category_id, language_code, name)
select c.id, v.language_code, v.name
from (
    values
    ('Bao Buns (2pcs)', 'tr', 'Bao Ekmekleri (2 adet)'),
    ('Beers', 'tr', 'Biralar'),
    ('Bites', 'tr', 'Atıştırmalıklar'),
    ('Burger & Sando (served with fries)', 'tr', 'Burger & Sando (patates kızartması ile)'),
    ('Champagne & Sparkling', 'tr', 'Şampanya ve Köpüklü Şaraplar'),
    ('Ciders', 'tr', 'Elma Şarapları (Cider)'),
    ('Classic Cocktails', 'tr', 'Klasik Kokteyller'),
    ('Crispy Fried Rolls (6pcs)', 'tr', 'Çıtır Kızarmış Rulolar (6 adet)'),
    ('Desserts', 'tr', 'Tatlılar'),
    ('Masao Cocktails', 'tr', 'Masao Kokteylleri'),
    ('Mocktails', 'tr', 'Alkolsüz Kokteyller'),
    ('Nigiri (2pcs)', 'tr', 'Nigiri (2 adet)'),
    ('Noodles', 'tr', 'Noodle'),
    ('Poke Bowl', 'tr', 'Poke Bowl'),
    ('Raw', 'tr', 'Çiğ Lezzetler'),
    ('Red Wines', 'tr', 'Kırmızı Şaraplar'),
    ('Rose Wines', 'tr', 'Roze Şaraplar'),
    ('Salads', 'tr', 'Salatalar'),
    ('Shisha', 'tr', 'Nargile'),
    ('Signature Rolls (8pcs)', 'tr', 'İmza Rulolar (8 adet)'),
    ('Soft Drinks', 'tr', 'Meşrubatlar'),
    ('Uramaki / Hossomaki (6pcs)', 'tr', 'Uramaki / Hossomaki (6 adet)'),
    ('Whiskey', 'tr', 'Viski'),
    ('White Wines', 'tr', 'Beyaz Şaraplar')
) as v(category_name, language_code, name)
join menu_categories c on c.name = v.category_name
on conflict (category_id, language_code) do nothing;

insert into menu_item_translations (menu_item_id, language_code, name, description)
select mi.id, v.language_code, v.name, v.description
from (
    values
    ('UR001', 'tr', 'Cucumber Maki', 'salatalık'),
    ('UR002', 'tr', 'Avocado Maki', 'avokado'),
    ('UR003', 'tr', 'Veggie Roll', 'salatalık, avokado, mango, taze soğan, krem peynir, yeşil tobiko'),
    ('UR004', 'tr', 'Vegan Roll', 'salatalık, avokado, mango, taze soğan, vegan mayonez, susam'),
    ('UR005', 'tr', 'California Salmon', 'somon, salatalık, avokado, krem peynir, susam'),
    ('UR006', 'tr', 'California Crab', 'yengeç kanimi, salatalık, avokado, krema mayonez, susam'),
    ('UR007', 'tr', 'Shrimp Tempura', 'karides tempura, avokado, acı mayonez, kırmızı masago'),
    ('UR008', 'tr', 'Tekka Kimchi', 'ton balığı, salatalık, kızarmış sarımsak, kimchi mayonez, kimchi susamı'),
    ('UR009', 'tr', 'Spicy Suzuki', 'levrek, salatalık, avokado, acı biberli mayonez, yuzu, tobiko'),
    ('NI001', 'tr', 'Avocado Nigiri', 'avokado'),
    ('NI002', 'tr', 'Salmon Nigiri', 'somon'),
    ('NI003', 'tr', 'Tuna Nigiri', 'ton balığı'),
    ('NI004', 'tr', 'Sea Bass Nigiri', 'levrek'),
    ('NI005', 'tr', 'Shrimp Nigiri', 'karides'),
    ('NI006', 'tr', 'Smoked Eel Nigiri', 'füme yılan balığı'),
    ('SR001', 'tr', 'Mango Mango', 'İçinde: karides tempura, krem peynir. Üzerinde: mango, çarkıfelek mayonezi, susam, frenk soğanı'),
    ('SR002', 'tr', 'Crab & Tuna', 'İçinde: ton balığı, avokado, salatalık, taze soğan. Üzerinde: yengeç, acı mayonez, frenk soğanı, çıtır soğan'),
    ('SR003', 'tr', 'Spicy Tuna', 'İçinde: ton balığı, avokado, salatalık. Üzerinde: ton balığı sashimi, acı mayonez, togarashi, frenk soğanı'),
    ('SR004', 'tr', 'Salmon Truffle', 'İçinde: somon, salatalık, taze soğan. Üzerinde: mühürlenmiş somon, unagi sos, trüf mayonezi, çıtır sarımsak, havyar'),
    ('SR005', 'tr', 'Phili Salmon', 'İçinde: somon, krem peynir, mango. Üzerinde: somon tartar, tatlı acı biberli mayonez, ikura, taze soğan'),
    ('SR006', 'tr', 'Suzuki & Shrimp', 'İçinde: karides tempura, krem peynir, mango. Üzerinde: mühürlenmiş levrek, tatlı-acı mayonez, teriyaki, taze soğan, tobiko'),
    ('SR007', 'tr', 'Crispy Shrimp', 'İçinde: karides tempura, taze soğan, krem peynir. Üzerinde: avokado, acı mayonez, çıtır soğan, frenk soğanı'),
    ('SR008', 'tr', 'Chicken Roll', 'İçinde: çıtır tavuk, iceberg marul, taze soğan. Üzerinde: avokado, çıtır soğan, hoisin mayonez'),
    ('SR009', 'tr', 'Masao', 'İçinde: karides tempura, avokado, taze soğan. Üzerinde: dana tartar, trüf mayonezi, çıtır soğan, frenk soğanı'),
    ('SR010', 'tr', 'Aegean Roll', 'İçinde: salatalık, avokado, beyaz peynir. Üzerinde: mühürlenmiş levrek, misket limonlu mayonez, zeytinyağı, dereotu, susam'),
    ('RAW001', 'tr', 'Sea Bass Carpaccio', 'levrek, narenciye, kırmızı biber, yuzu, acı biber, zeytinyağı, limon, dereotu'),
    ('RAW002', 'tr', 'Salmon Yuzu', 'somon, ikura, misket limonu kabuğu rendesi, taze soğan, mango, yuzu, susam'),
    ('RAW003', 'tr', 'Tuna Turf', 'ton balığı, trüf yağı, çeri domates, maydanoz, taze soğan'),
    ('RAW004', 'tr', 'Variety of Sashimi 12pcs', 'somon, ton balığı, levrek'),
    ('CF001', 'tr', 'Crispy Tekka Roll', 'İçinde: ton balığı, salatalık, krem peynir. Üzerinde: acı mayonez, teriyaki, frenk soğanı'),
    ('CF002', 'tr', 'Crunchy Salmon Roll', 'İçinde: somon, krem peynir, avokado. Üzerinde: hoisin mayonez, frenk soğanı'),
    ('CF003', 'tr', 'Crispy Veggie Roll', 'İçinde: salatalık, krem peynir, avokado. Üzerinde: hoisin mayonez, frenk soğanı'),
    ('BI001', 'tr', 'Chicken Dumplings', 'trüflü ponzu sos, taze soğan'),
    ('BI002', 'tr', 'Spring Rolls', 'sebzeli çin böreği, tatlı acı biber sosu'),
    ('BI003', 'tr', 'Shrimp Gyoza', 'acı biberli soya sosu, frenk soğanı'),
    ('BI004', 'tr', 'Crispy Cheese Wonton', 'karides, yengeç, krem peynir'),
    ('BAO001', 'tr', 'Shrimp Bao', 'karides tempura, salatalık, avokado kreması, marul, acı mayonez, frenk soğanı, susam'),
    ('BAO002', 'tr', 'Chicken Bao', 'çıtır tavuk, salatalık, avokado kreması, marul, acı mayonez, frenk soğanı, çıtır soğan'),
    ('BAO003', 'tr', 'Salmon Bao', 'teriyaki somon, salatalık, marul, avokado, misket limonlu mayonez, frenk soğanı, çıtır soğan'),
    ('BAO004', 'tr', 'Mushroom Bao', 'mantar, salatalık, hoisin mayonez, taze soğan, susam'),
    ('BAO005', 'tr', 'Duck Bao', 'çıtır ördek, salatalık, marul, havuç, erik sosu, frenk soğanı, susam'),
    ('NO001', 'tr', 'Veggie Noodles', 'lahana, soğan, havuç, biber, minik mısır, noodle, susam yağı, teriyaki sos'),
    ('NO002', 'tr', 'Chicken Noodles', 'lahana, soğan, havuç, biber, minik mısır, yumurtalı noodle, susam yağı, teriyaki sos'),
    ('NO003', 'tr', 'Shrimp Noodles', 'lahana, soğan, havuç, biber, minik mısır, noodle, susam yağı, teriyaki sos'),
    ('NO004', 'tr', 'Mushroom Yaki Udon', 'mantar, udon noodle, taze soğan, sarımsak, zencefil, unagi sos'),
    ('NO005', 'tr', 'Salmon Yaki Udon', 'glaze somon fileto, udon noodle, taze soğan, havuç, biber, sarımsak, zencefil, unagi sos'),
    ('NO006', 'tr', 'Beef Yaki Udon', 'kıyılmış dana eti, udon noodle, taze soğan, sarımsak, zencefil, unagi sos'),
    ('BU001', 'tr', 'Beef Melt', 'black angus dana burger, brioche ekmeği, iceberg marul, jalapeño biberi, cheddar peyniri, hoisin mayonez'),
    ('BU002', 'tr', 'Beef Truffle', 'black angus dana burger, brioche ekmeği, karışık yeşillik, parmesan peyniri, trüf mayonezi'),
    ('BU003', 'tr', 'Chicken Katsu Sando', 'çıtır tavuk but, brioche ekmeği, salatalık turşusu, iceberg marul, hoisin mayonez'),
    ('BU004', 'tr', 'Shrimp & Crab Sando Roll', 'karides, yengeç, brioche ekmeği, iceberg marul, kırmızı soğan turşusu, çıtır sarımsak, frenk soğanı, acı mayonez'),
    ('PO001', 'tr', 'Salmon Poke Bowl', 'suşi pilavı, marine somon, avokado, salatalık, mango, edamame, wakame, tobiko, frenk soğanı, misket limonu, susam, acı mayonez'),
    ('PO002', 'tr', 'Shrimp-Crab Poke Bowl', 'suşi pilavı, haşlanmış karides, yengeç kanimi, avokado, salatalık, mango, edamame, wakame, tobiko, frenk soğanı, misket limonu, susam, acı mayonez'),
    ('PO003', 'tr', 'Chicken Poke Bowl', 'suşi pilavı, çıtır tavuk, salatalık, avokado, tatlı mısır, taze soğan, deniz yosunu, mango, havuç, mayonez, susam'),
    ('SA001', 'tr', 'Edamame', 'buharda pişmiş edamame, tuz pulu'),
    ('SA002', 'tr', 'Kanimi Salad', 'yengeç kanimi, marul, salatalık, taze soğan, acı biber, çıtır pirinç, çıtır sarımsak, susam sosu'),
    ('SA003', 'tr', 'Emperor Salad', 'çıtır tavuk, iceberg, marul, avokado, çıtır pastırma, kaju, parmesan sos'),
    ('SA004', 'tr', 'Kaiso Salad', 'wakame deniz yosunu, susam'),
    ('SA005', 'tr', 'Shrimp Noodle Salad', 'karides, karışık yeşillik, mendake noodle, edamame, avokado, parmesan, biber, acı misket limonu sosu'),
    ('SA006', 'tr', 'Tropical Shrimp Salad', 'karides, salatalık, mango, avokado, karışık yeşillik, çarkıfelek mayonezi, susam'),
    ('DE001', 'tr', 'Chocolate Fondant', 'antep fıstıklı dondurma ve krema ile servis edilir'),
    ('DE002', 'tr', 'Baked Cheesecake', 'kırmızı meyveli dondurma ve orman meyveleri ile servis edilir'),
    ('DE003', 'tr', 'Tiramisu', 'vanilyalı dondurma ve krema ile servis edilir'),
    ('CO001', 'tr', 'Okinawa', 'Japon Yuzu Aperatifi, Shiso, Mürver Çiçeği, Gazlı Sake, Çilek'),
    ('CO002', 'tr', 'Chihaya', 'Don Julio Tequila Blanco, Kakule-Hardal, Kiraz, Kuruyemiş, Erik Bitteri, Bulutlar'),
    ('CO003', 'tr', 'Shirakawa', 'Baharatlı Ketel One Votka, Hibiskus, Rom, Orman Meyveleri, Zencefil Köpüğü'),
    ('CO004', 'tr', 'Tsumago', 'Johnnie Walker Black Label, Duman, Ananas, Jalapeño, Bal, Limon Suyu'),
    ('CO005', 'tr', 'ギリシャ (Girisha)', 'Sakız Rakısı (Mastiha), Oolong Çayı, Narenciyeli Ponzu, Şeftali Turşusu, Aromatik Bitter'),
    ('CO006', 'tr', 'Japanese Opioum', 'Votka, Ağaç Kavunu Likörü, Yasemin Şurubu, Misket Limonu Suyu, Yeşil Elma Likörü'),
    ('CO007', 'tr', 'Yugen', 'Tanqueray No. 10 Cin, Mandalina, Botanikler, Limon Suyu, Yuzu-Hindistan Cevizi Köpüğü'),
    ('CO008', 'tr', 'Kintsugi Sour', 'Johnnie Walker Black Ruby, Vanilya, Muz, Limon Kabuğu, Misket Limonu, Bulutlar'),
    ('CO009', 'tr', 'Tsukimi Glow', 'Tanqueray Cin, Çarkıfelek Meyvesi, Ravent Likörü, Pembe Greyfurt Sodası'),
    ('CO010', 'tr', 'Amaterasu Light', 'Captain Morgan Rom, Zacapa Rom, Kavun, Limon Suyu, Nane Yaprakları'),
    ('CC001', 'tr', 'Margarita', 'Tekila, triple sec, misket limonu suyu, tuzlu kenar'),
    ('CC002', 'tr', 'Daiquiri', 'Rom, misket limonu suyu, şeker'),
    ('CC003', 'tr', 'Porn Star Martini', 'Vanilyalı votka, çarkıfelek likörü, çarkıfelek meyvesi, prosecco'),
    ('CC004', 'tr', 'Gin Basil Smash', 'Cin, taze fesleğen, limon suyu, şeker şurubu'),
    ('CC005', 'tr', 'Paloma', 'Tekila, greyfurt sodası, misket limonu suyu, tuz'),
    ('CC006', 'tr', 'Mai Tai', 'Rom, portakallı curaçao, misket limonu suyu, orgeat şurubu'),
    ('CC007', 'tr', 'Zombie', 'Üç çeşit rom, meyve suları, grenadin'),
    ('CC008', 'tr', 'Espresso Martini', 'Votka, kahve likörü, espresso, şeker şurubu'),
    ('CC009', 'tr', 'Long Drinks', 'Klasik long drink seçkisi'),
    ('MO001', 'tr', 'Takaragawa', 'Tanqueray %0, kiraz, şeftali turşusu'),
    ('MO002', 'tr', 'Bonsai Breeze', 'Tanqueray %0, çarkıfelek meyvesi, mandalina, siyah çay, limon suyu'),
    ('DR001', 'tr', 'Still Water 1lt', 'Doğal kaynak suyu 1 litre'),
    ('DR002', 'tr', 'S.Pellegrino 750ml', 'Doğal maden sodası 750 ml'),
    ('DR003', 'tr', 'Three Cents Pink Grapefruit Soda', 'Pembe greyfurt sodası 200 ml'),
    ('DR004', 'tr', 'Espresso', 'Espresso kahve'),
    ('DR005', 'tr', 'Tea', 'Çay'),
    ('CI001', 'tr', 'Milokleftis Greek Apple Cider', 'Yunan elma şarabı (cider), 330 ml, %4,5 alkol'),
    ('CI002', 'tr', 'Strongbow Red Berries Cider', 'Kırmızı orman meyveli cider, 330 ml, %4,5 alkol'),
    ('BE001', 'tr', 'Heineken Draft', 'Fıçı lager, 400 ml, %5 alkol'),
    ('BE002', 'tr', 'Alfa Lager', 'Yunan lager birası, 330 ml, %5 alkol'),
    ('BE003', 'tr', 'Amstel Radler', 'Limonlu radler, 330 ml, %4,2 alkol'),
    ('BE004', 'tr', 'Mamos Pilsner', 'Pilsner, 330 ml, %5 alkol'),
    ('BE005', 'tr', 'Erdinger Weiss', 'Buğday birası, 330 ml, %5,3 alkol'),
    ('BE006', 'tr', 'Sol Exotic Lager', 'Egzotik lager, 330 ml, %4,2 alkol'),
    ('BE007', 'tr', 'Asahi Dry Japanese Beer', 'Sek Japon birası, 330 ml'),
    ('WH001', 'tr', 'Johnnie Walker Red Label', 'Harman İskoç viskisi'),
    ('WH002', 'tr', 'Johnnie Walker Black Label', 'Harman İskoç viskisi, 12 yıllık'),
    ('WH003', 'tr', 'Dewar''s', 'Harman İskoç viskisi'),
    ('WH004', 'tr', 'Metaxa 5 Stars', 'Yıllandırılmış Yunan içkisi'),
    ('WW001', 'tr', 'Oinos Grigoriadi', 'Sauvignon Blanc, Assyrtiko · kadeh: 7€'),
    ('WW002', 'tr', 'Monolithos | Bairaktaris Winery', 'Malagouzia, Assyrtiko, Misket · kadeh: 7€'),
    ('WW003', 'tr', 'Propodes | Domaine Zafeirakis', 'Chardonnay'),
    ('WW004', 'tr', 'Megathiri | Tatakis Wines', 'Athiri'),
    ('WW005', 'tr', 'Theros Wine Collectiva', 'Thrapsathiri'),
    ('WW006', 'tr', 'Ktima Gerovasiliou', 'Malagouzia, Assyrtiko'),
    ('WW007', 'tr', 'Akrathos Newlands Winery', 'Assyrtiko'),
    ('WW008', 'tr', 'Domaine Costa Lazaridi', 'Semillon'),
    ('WW009', 'tr', 'Le Bouquet | Domaine Laporte', 'Sauvignon Blanc'),
    ('WW010', 'tr', 'Weingut Thorle', 'Riesling yarı sek'),
    ('WW011', 'tr', 'Bourgogne / Domaine David Moret', 'Chardonnay'),
    ('RO001', 'tr', '4-6H | Gaia Wines', 'Agiorgitiko roze · kadeh: 7€'),
    ('RO002', 'tr', 'Joker Semi Dry | Liappis Boutique Winery', 'Misket, Syrah roze · kadeh: 7€'),
    ('RO003', 'tr', 'Maissa | Tatakis Wines', 'Syrah, Merlot roze'),
    ('RO004', 'tr', 'Techni Alipias | Wine Art Estate', 'Syrah roze'),
    ('RO005', 'tr', 'Domaine Costa Lazaridi Rosé', 'Merlot, Agiorgitiko, Syrah roze'),
    ('RO006', 'tr', 'Alpha Estate', 'Xinomavro roze'),
    ('RO007', 'tr', 'Miraval | Chateau Miraval', 'Grenache Rouge, Cinsault, Syrah roze'),
    ('RO008', 'tr', 'M de Minuty | Chateau Minuty', 'Cinsault, Grenache, Mourvèdre, Rolle roze'),
    ('RE001', 'tr', 'Kompsos | Karavitakis Winery', 'Liatiko kırmızı · kadeh: 7€'),
    ('RE002', 'tr', 'Kokkini Porta | Tatakis Wines Rhodes', 'Mandilaria, Merlot kırmızı'),
    ('RE003', 'tr', 'Feggites | Oenogenesis Winery', 'Cabernet Sauvignon, Cabernet Franc, Merlot'),
    ('SP001', 'tr', 'Martini Prosecco D.O.C', 'Prosecco · kadeh: 8€'),
    ('SP002', 'tr', 'Martini Asti Semi Sweet', 'Yarı tatlı köpüklü şarap · kadeh: 8€'),
    ('SP003', 'tr', 'Moët & Chandon Ice Imperial', 'Buz üzerinde servis edilen şampanya'),
    ('SP004', 'tr', 'Moët & Chandon Rosé Imperial Brut', 'Roze Şampanya Brut'),
    ('SP005', 'tr', 'Louis Roederer Brut Collection', 'Şampanya Brut Collection'),
    ('SH001', 'tr', 'Nargile', 'Mevcut aromalar: Blue ice, Forest pulp (çilek, orman meyveleri), Alter ego (orman meyveleri, mango, nane), Knock out (çarkıfelek, mango), Karpuz, Şeftali, Limon nane, İki elma (yeşil, kırmızı)')
) as v(external_id, language_code, name, description)
join menu_items mi on mi.external_id = v.external_id
on conflict (menu_item_id, language_code) do nothing;

commit;
