import type { Lang } from "@/i18n/config";

export type OrderCopy = {
  modeTitle: string;
  dineIn: string;
  dineInHint: string;
  takeAway: string;
  takeAwayHint: string;
  takeawayTitle: string;
  name: string;
  namePlaceholder: string;
  phone: string;
  phonePlaceholder: string;
  confirm: string;
  sending: string;
  successTitle: string;
  successBody: string;
  errorRequired: string;
  errorSend: string;
  back: string;
  done: string;
};

export const ORDER_COPY: Record<Lang, OrderCopy> = {
  el: {
    modeTitle: "Πώς θα το απολαύσετε;",
    dineIn: "Στο κατάστημα",
    dineInHint: "Δείξτε την παραγγελία στον σερβιτόρο",
    takeAway: "Take away",
    takeAwayHint: "Στείλτε την παραγγελία και περάστε να την πάρετε",
    takeawayTitle: "Παραγγελία take away",
    name: "Όνομα",
    namePlaceholder: "Το όνομά σας",
    phone: "Τηλέφωνο",
    phonePlaceholder: "π.χ. 6912345678",
    confirm: "Επιβεβαίωση παραγγελίας",
    sending: "Αποστολή…",
    successTitle: "Η παραγγελία στάλθηκε",
    successBody: "Πήραμε την παραγγελία σας! Θα σας πάρουμε τηλέφωνο μόλις είναι έτοιμη.",
    errorRequired: "Συμπληρώστε όνομα και τηλέφωνο.",
    errorSend: "Η παραγγελία δεν στάλθηκε. Δοκιμάστε ξανά ή καλέστε μας.",
    back: "Πίσω",
    done: "Κλείσιμο",
  },
  en: {
    modeTitle: "How would you like it?",
    dineIn: "Dine in",
    dineInHint: "Show your order to the waiter",
    takeAway: "Take away",
    takeAwayHint: "Send your order and pick it up",
    takeawayTitle: "Take-away order",
    name: "Name",
    namePlaceholder: "Your name",
    phone: "Phone",
    phonePlaceholder: "e.g. +30 691 234 5678",
    confirm: "Confirm order",
    sending: "Sending…",
    successTitle: "Order sent",
    successBody: "We've received your order! We'll give you a call as soon as it's ready.",
    errorRequired: "Please fill in your name and phone number.",
    errorSend: "The order was not sent. Please try again or call us.",
    back: "Back",
    done: "Close",
  },
  de: {
    modeTitle: "Wie möchten Sie bestellen?",
    dineIn: "Im Restaurant",
    dineInHint: "Zeigen Sie Ihre Bestellung dem Kellner",
    takeAway: "Zum Mitnehmen",
    takeAwayHint: "Bestellung senden und abholen",
    takeawayTitle: "Bestellung zum Mitnehmen",
    name: "Name",
    namePlaceholder: "Ihr Name",
    phone: "Telefon",
    phonePlaceholder: "z. B. +30 691 234 5678",
    confirm: "Bestellung bestätigen",
    sending: "Wird gesendet…",
    successTitle: "Bestellung gesendet",
    successBody: "Wir haben Ihre Bestellung erhalten! Wir rufen Sie an, sobald sie fertig ist.",
    errorRequired: "Bitte Name und Telefonnummer angeben.",
    errorSend: "Die Bestellung wurde nicht gesendet. Bitte erneut versuchen oder anrufen.",
    back: "Zurück",
    done: "Schließen",
  },
  it: {
    modeTitle: "Come preferisci?",
    dineIn: "Al ristorante",
    dineInHint: "Mostra l'ordine al cameriere",
    takeAway: "Da asporto",
    takeAwayHint: "Invia l'ordine e passa a ritirarlo",
    takeawayTitle: "Ordine da asporto",
    name: "Nome",
    namePlaceholder: "Il tuo nome",
    phone: "Telefono",
    phonePlaceholder: "es. +30 691 234 5678",
    confirm: "Conferma ordine",
    sending: "Invio…",
    successTitle: "Ordine inviato",
    successBody: "Abbiamo ricevuto il tuo ordine! Ti chiameremo appena sarà pronto.",
    errorRequired: "Inserisci nome e numero di telefono.",
    errorSend: "L'ordine non è stato inviato. Riprova o chiamaci.",
    back: "Indietro",
    done: "Chiudi",
  },
  sv: {
    modeTitle: "Hur vill du ha det?",
    dineIn: "Äta här",
    dineInHint: "Visa din beställning för kyparen",
    takeAway: "Ta med",
    takeAwayHint: "Skicka beställningen och hämta den",
    takeawayTitle: "Avhämtningsbeställning",
    name: "Namn",
    namePlaceholder: "Ditt namn",
    phone: "Telefon",
    phonePlaceholder: "t.ex. +30 691 234 5678",
    confirm: "Bekräfta beställning",
    sending: "Skickar…",
    successTitle: "Beställningen är skickad",
    successBody: "Vi har tagit emot din beställning! Vi ringer dig så snart den är klar.",
    errorRequired: "Fyll i namn och telefonnummer.",
    errorSend: "Beställningen skickades inte. Försök igen eller ring oss.",
    back: "Tillbaka",
    done: "Stäng",
  },
  fr: {
    modeTitle: "Comment souhaitez-vous commander ?",
    dineIn: "Sur place",
    dineInHint: "Montrez votre commande au serveur",
    takeAway: "À emporter",
    takeAwayHint: "Envoyez votre commande et venez la chercher",
    takeawayTitle: "Commande à emporter",
    name: "Nom",
    namePlaceholder: "Votre nom",
    phone: "Téléphone",
    phonePlaceholder: "ex. +30 691 234 5678",
    confirm: "Confirmer la commande",
    sending: "Envoi…",
    successTitle: "Commande envoyée",
    successBody: "Nous avons bien reçu votre commande ! Nous vous appellerons dès qu'elle sera prête.",
    errorRequired: "Veuillez indiquer votre nom et votre téléphone.",
    errorSend: "La commande n'a pas été envoyée. Réessayez ou appelez-nous.",
    back: "Retour",
    done: "Fermer",
  },
  ru: {
    modeTitle: "Как вам удобнее?",
    dineIn: "В ресторане",
    dineInHint: "Покажите заказ официанту",
    takeAway: "С собой",
    takeAwayHint: "Отправьте заказ и заберите его",
    takeawayTitle: "Заказ с собой",
    name: "Имя",
    namePlaceholder: "Ваше имя",
    phone: "Телефон",
    phonePlaceholder: "напр. +30 691 234 5678",
    confirm: "Подтвердить заказ",
    sending: "Отправка…",
    successTitle: "Заказ отправлен",
    successBody: "Мы получили ваш заказ! Позвоним вам, как только он будет готов.",
    errorRequired: "Укажите имя и номер телефона.",
    errorSend: "Заказ не отправлен. Попробуйте снова или позвоните нам.",
    back: "Назад",
    done: "Закрыть",
  },
  he: {
    modeTitle: "איך נוח לכם?",
    dineIn: "במסעדה",
    dineInHint: "הציגו את ההזמנה למלצר",
    takeAway: "טייק אוויי",
    takeAwayHint: "שלחו את ההזמנה ובואו לאסוף",
    takeawayTitle: "הזמנת טייק אוויי",
    name: "שם",
    namePlaceholder: "השם שלכם",
    phone: "טלפון",
    phonePlaceholder: "לדוגמה ‎+30 691 234 5678",
    confirm: "אישור הזמנה",
    sending: "שולח…",
    successTitle: "ההזמנה נשלחה",
    successBody: "קיבלנו את ההזמנה שלכם! נתקשר אליכם ברגע שהיא תהיה מוכנה.",
    errorRequired: "יש למלא שם וטלפון.",
    errorSend: "ההזמנה לא נשלחה. נסו שוב או התקשרו אלינו.",
    back: "חזרה",
    done: "סגירה",
  },
  tr: {
    modeTitle: "Nasıl tercih edersiniz?",
    dineIn: "Restoranda",
    dineInHint: "Siparişinizi garsona gösterin",
    takeAway: "Paket servis",
    takeAwayHint: "Siparişinizi gönderin ve gelip alın",
    takeawayTitle: "Paket sipariş",
    name: "Ad",
    namePlaceholder: "Adınız",
    phone: "Telefon",
    phonePlaceholder: "örn. +30 691 234 5678",
    confirm: "Siparişi onayla",
    sending: "Gönderiliyor…",
    successTitle: "Sipariş gönderildi",
    successBody: "Siparişinizi aldık! Hazır olduğunda sizi arayacağız.",
    errorRequired: "Lütfen ad ve telefon numarası girin.",
    errorSend: "Sipariş gönderilemedi. Tekrar deneyin veya bizi arayın.",
    back: "Geri",
    done: "Kapat",
  },
};
