import type { Lang } from "@/i18n/config";

export type PickupSlot = "asap" | "in_30" | "in_60";

export type OrderCopy = {
  modeTitle: string;
  dineIn: string;
  dineInHint: string;
  takeAway: string;
  takeAwayHint: string;
  takeawayTitle: string;
  name: string;
  namePlaceholder: string;
  phone: string;
  phonePlaceholder: string;
  pickup: string;
  pickupAsap: string;
  pickup30: string;
  pickup60: string;
  confirm: string;
  sending: string;
  successTitle: string;
  successBody: string;
  errorRequired: string;
  errorSend: string;
  back: string;
  done: string;
};

export const ORDER_COPY: Record<Lang, OrderCopy> = {
  el: {
    modeTitle: "Πώς θα το απολαύσετε;",
    dineIn: "Στο κατάστημα",
    dineInHint: "Δείξτε την παραγγελία στον σερβιτόρο",
    takeAway: "Take away",
    takeAwayHint: "Στείλτε την παραγγελία και περάστε να την πάρετε",
    takeawayTitle: "Παραγγελία take away",
    name: "Όνομα",
    namePlaceholder: "Το όνομά σας",
    phone: "Τηλέφωνο",
    phonePlaceholder: "π.χ. 6912345678",
    pickup: "Ώρα παραλαβής",
    pickupAsap: "Το συντομότερο",
    pickup30: "Σε 30 λεπτά",
    pickup60: "Σε 60 λεπτά",
    confirm: "Επιβεβαίωση παραγγελίας",
    sending: "Αποστολή…",
    successTitle: "Η παραγγελία στάλθηκε",
    successBody: "Θα είναι έτοιμη την ώρα που επιλέξατε. Θα σας καλέσουμε αν χρειαστεί.",
    errorRequired: "Συμπληρώστε όνομα και τηλέφωνο.",
    errorSend: "Η παραγγελία δεν στάλθηκε. Δοκιμάστε ξανά ή καλέστε μας.",
    back: "Πίσω",
    done: "Κλείσιμο",
  },
  en: {
    modeTitle: "How would you like it?",
    dineIn: "Dine in",
    dineInHint: "Show your order to the waiter",
    takeAway: "Take away",
    takeAwayHint: "Send your order and pick it up",
    takeawayTitle: "Take-away order",
    name: "Name",
    namePlaceholder: "Your name",
    phone: "Phone",
    phonePlaceholder: "e.g. +30 691 234 5678",
    pickup: "Pickup time",
    pickupAsap: "As soon as possible",
    pickup30: "In 30 minutes",
    pickup60: "In 60 minutes",
    confirm: "Confirm order",
    sending: "Sending…",
    successTitle: "Order sent",
    successBody: "It will be ready at the time you chose. We'll call you if we need to.",
    errorRequired: "Please fill in your name and phone number.",
    errorSend: "The order was not sent. Please try again or call us.",
    back: "Back",
    done: "Close",
  },
  de: {
    modeTitle: "Wie möchten Sie bestellen?",
    dineIn: "Im Restaurant",
    dineInHint: "Zeigen Sie Ihre Bestellung dem Kellner",
    takeAway: "Zum Mitnehmen",
    takeAwayHint: "Bestellung senden und abholen",
    takeawayTitle: "Bestellung zum Mitnehmen",
    name: "Name",
    namePlaceholder: "Ihr Name",
    phone: "Telefon",
    phonePlaceholder: "z. B. +30 691 234 5678",
    pickup: "Abholzeit",
    pickupAsap: "So bald wie möglich",
    pickup30: "In 30 Minuten",
    pickup60: "In 60 Minuten",
    confirm: "Bestellung bestätigen",
    sending: "Wird gesendet…",
    successTitle: "Bestellung gesendet",
    successBody: "Sie ist zur gewählten Zeit fertig. Wir rufen an, falls nötig.",
    errorRequired: "Bitte Name und Telefonnummer angeben.",
    errorSend: "Die Bestellung wurde nicht gesendet. Bitte erneut versuchen oder anrufen.",
    back: "Zurück",
    done: "Schließen",
  },
  it: {
    modeTitle: "Come preferisci?",
    dineIn: "Al ristorante",
    dineInHint: "Mostra l'ordine al cameriere",
    takeAway: "Da asporto",
    takeAwayHint: "Invia l'ordine e passa a ritirarlo",
    takeawayTitle: "Ordine da asporto",
    name: "Nome",
    namePlaceholder: "Il tuo nome",
    phone: "Telefono",
    phonePlaceholder: "es. +30 691 234 5678",
    pickup: "Orario di ritiro",
    pickupAsap: "Il prima possibile",
    pickup30: "Tra 30 minuti",
    pickup60: "Tra 60 minuti",
    confirm: "Conferma ordine",
    sending: "Invio…",
    successTitle: "Ordine inviato",
    successBody: "Sarà pronto all'orario scelto. Ti chiameremo se necessario.",
    errorRequired: "Inserisci nome e numero di telefono.",
    errorSend: "L'ordine non è stato inviato. Riprova o chiamaci.",
    back: "Indietro",
    done: "Chiudi",
  },
  sv: {
    modeTitle: "Hur vill du ha det?",
    dineIn: "Äta här",
    dineInHint: "Visa din beställning för kyparen",
    takeAway: "Ta med",
    takeAwayHint: "Skicka beställningen och hämta den",
    takeawayTitle: "Avhämtningsbeställning",
    name: "Namn",
    namePlaceholder: "Ditt namn",
    phone: "Telefon",
    phonePlaceholder: "t.ex. +30 691 234 5678",
    pickup: "Avhämtningstid",
    pickupAsap: "Så snart som möjligt",
    pickup30: "Om 30 minuter",
    pickup60: "Om 60 minuter",
    confirm: "Bekräfta beställning",
    sending: "Skickar…",
    successTitle: "Beställningen är skickad",
    successBody: "Den är klar vid vald tid. Vi ringer om det behövs.",
    errorRequired: "Fyll i namn och telefonnummer.",
    errorSend: "Beställningen skickades inte. Försök igen eller ring oss.",
    back: "Tillbaka",
    done: "Stäng",
  },
  fr: {
    modeTitle: "Comment souhaitez-vous commander ?",
    dineIn: "Sur place",
    dineInHint: "Montrez votre commande au serveur",
    takeAway: "À emporter",
    takeAwayHint: "Envoyez votre commande et venez la chercher",
    takeawayTitle: "Commande à emporter",
    name: "Nom",
    namePlaceholder: "Votre nom",
    phone: "Téléphone",
    phonePlaceholder: "ex. +30 691 234 5678",
    pickup: "Heure de retrait",
    pickupAsap: "Dès que possible",
    pickup30: "Dans 30 minutes",
    pickup60: "Dans 60 minutes",
    confirm: "Confirmer la commande",
    sending: "Envoi…",
    successTitle: "Commande envoyée",
    successBody: "Elle sera prête à l'heure choisie. Nous vous appellerons si besoin.",
    errorRequired: "Veuillez indiquer votre nom et votre téléphone.",
    errorSend: "La commande n'a pas été envoyée. Réessayez ou appelez-nous.",
    back: "Retour",
    done: "Fermer",
  },
  ru: {
    modeTitle: "Как вам удобнее?",
    dineIn: "В ресторане",
    dineInHint: "Покажите заказ официанту",
    takeAway: "С собой",
    takeAwayHint: "Отправьте заказ и заберите его",
    takeawayTitle: "Заказ с собой",
    name: "Имя",
    namePlaceholder: "Ваше имя",
    phone: "Телефон",
    phonePlaceholder: "напр. +30 691 234 5678",
    pickup: "Время получения",
    pickupAsap: "Как можно скорее",
    pickup30: "Через 30 минут",
    pickup60: "Через 60 минут",
    confirm: "Подтвердить заказ",
    sending: "Отправка…",
    successTitle: "Заказ отправлен",
    successBody: "Он будет готов к выбранному времени. Мы позвоним, если понадобится.",
    errorRequired: "Укажите имя и номер телефона.",
    errorSend: "Заказ не отправлен. Попробуйте снова или позвоните нам.",
    back: "Назад",
    done: "Закрыть",
  },
  he: {
    modeTitle: "איך נוח לכם?",
    dineIn: "במסעדה",
    dineInHint: "הציגו את ההזמנה למלצר",
    takeAway: "טייק אוויי",
    takeAwayHint: "שלחו את ההזמנה ובואו לאסוף",
    takeawayTitle: "הזמנת טייק אוויי",
    name: "שם",
    namePlaceholder: "השם שלכם",
    phone: "טלפון",
    phonePlaceholder: "לדוגמה ‎+30 691 234 5678",
    pickup: "שעת איסוף",
    pickupAsap: "בהקדם האפשרי",
    pickup30: "בעוד 30 דקות",
    pickup60: "בעוד 60 דקות",
    confirm: "אישור הזמנה",
    sending: "שולח…",
    successTitle: "ההזמנה נשלחה",
    successBody: "היא תהיה מוכנה בשעה שבחרתם. נתקשר אם יהיה צורך.",
    errorRequired: "יש למלא שם וטלפון.",
    errorSend: "ההזמנה לא נשלחה. נסו שוב או התקשרו אלינו.",
    back: "חזרה",
    done: "סגירה",
  },
  tr: {
    modeTitle: "Nasıl tercih edersiniz?",
    dineIn: "Restoranda",
    dineInHint: "Siparişinizi garsona gösterin",
    takeAway: "Paket servis",
    takeAwayHint: "Siparişinizi gönderin ve gelip alın",
    takeawayTitle: "Paket sipariş",
    name: "Ad",
    namePlaceholder: "Adınız",
    phone: "Telefon",
    phonePlaceholder: "örn. +30 691 234 5678",
    pickup: "Teslim alma saati",
    pickupAsap: "En kısa sürede",
    pickup30: "30 dakika içinde",
    pickup60: "60 dakika içinde",
    confirm: "Siparişi onayla",
    sending: "Gönderiliyor…",
    successTitle: "Sipariş gönderildi",
    successBody: "Seçtiğiniz saatte hazır olacak. Gerekirse sizi arayacağız.",
    errorRequired: "Lütfen ad ve telefon numarası girin.",
    errorSend: "Sipariş gönderilemedi. Tekrar deneyin veya bizi arayın.",
    back: "Geri",
    done: "Kapat",
  },
};

export function pickupLabel(copy: OrderCopy, slot: PickupSlot): string {
  if (slot === "in_30") return copy.pickup30;
  if (slot === "in_60") return copy.pickup60;
  return copy.pickupAsap;
}
